feat: add Transform Status Code Policy
gravitee-io/gravitee-api-management pull request #10004
Opened 2024-11-28 14:20 UTC by illichso

## Issue

https://gravitee.atlassian.net/browse/APIM-5451

## Description

As an API publisher

I want to transform the status code sent from the upstream service from one HTTP status to another

so that I can send a response that I want to the client if I can’t change the upstream response.

## Additional context

2024-11-28 14:22 UTC, phiz71 requested changes

2024-11-28 14:22 UTC, phiz71 commented on pom.xml
> +        <gravitee-policy-transform-status-code.version>1.0.0-alpha.1</gravitee-policy-transform-status-code.version>
we should not use alpha version if the policy is put on the community bundle or the default bundle.
As we discussed together, we should first add this policy in bundle-dev profile

2024-11-29 10:12 UTC, graviteeio commented on gravitee-apim-portal-webui/dist-next/browser/polyfills-L5LZC3JG.js
> +(function(e){let t=e.performance;function o(L){t&&t.mark&&t.mark(L)}function r(L,n){t&&t.measure&&t.measure(L,n)}o("Zone");let a=e.__Zone_symbol_prefix||"__zone_symbol__";function l(L){return a+L}let
### :warning: Aqua detected sensitive data in your code  
**Category:** Azure   
**Description:** Azure SAS Token   
**Severity:** HIGH   
**Match:** y loaded.");return e.Zone}let ******** se{static assertZon  
[This comment was created by Aqua Pipeline]

2024-11-29 10:45 UTC, phiz71 approved these changes

2024-11-29 11:22 UTC, merged