feat: upgrade jdk version
gravitee-io/gravitee-api-management pull request #10075
Opened 2024-12-06 13:42 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-425

## Description

BREAKING CHANGE: jdk used for compilation needs to be upgrade to 21

## Additional context

2025-01-13 17:37 UTC, jhaeyaert requested changes

2025-01-13 17:37 UTC, jhaeyaert commented on gravitee-apim-gateway/docker/Dockerfile
> +    && if [ $(apk --print-arch) = "aarch64" ]; then ln -s /lib/libc.musl-aarch64.so.1 /lib/ld-linux-aarch64.so.2; fi
Can use the variable assigned previously no?
`&& if [ $(apkArch) = "aarch64" ]; then ln -s /lib/libc.musl-aarch64.so.1 /lib/ld-linux-aarch64.so.2; fi` 

Out of curiosity, does it mean that there is no need for an additional link for other architectures?

2025-01-15 13:47 UTC, phiz71 commented on gravitee-apim-gateway/docker/Dockerfile
> +    && if [ $(apk --print-arch) = "aarch64" ]; then ln -s /lib/libc.musl-aarch64.so.1 /lib/ld-linux-aarch64.so.2; fi
should we also have a look to this PR in the same time ?
https://github.com/gravitee-io/gravitee-api-management/pull/9857

2025-01-16 10:18 UTC, guillaumelamirand commented on gravitee-apim-gateway/docker/Dockerfile
> +    && if [ $(apk --print-arch) = "aarch64" ]; then ln -s /lib/libc.musl-aarch64.so.1 /lib/ld-linux-aarch64.so.2; fi
> Can use the variable assigned previously no? `&& if [ $(apkArch) = "aarch64" ]; then ln -s /lib/libc.musl-aarch64.so.1 /lib/ld-linux-aarch64.so.2; fi`
> 
> Out of curiosity, does it mean that there is no need for an additional link for other architectures?

I did it on the other DockerFile and forgot about this one. I fixed it.

2025-01-20 14:26 UTC, jhaeyaert approved these changes

2025-01-20 14:28 UTC, phiz71 approved these changes

2025-01-20 15:05 UTC, merged