fix: restore API primary owner privileges
gravitee-io/gravitee-api-management pull request #1069
Opened 2022-01-10 16:09 UTC by a-cordier

According to the documentation, API primary owner is by default the only
user to be able to delete an API or update its context path. The default
permissions for the `OWNER` role have been updated accordingly.

see https://github.com/gravitee-io/issues/issues/6360

2022-02-02 10:00 UTC, phiz71 requested changes

2022-02-02 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/common/DefaultRoleEntityDefinition.java
> +            .put(ApiPermission.GATEWAY_DEFINITION.getName(), new char[] { CREATE.getId(), READ.getId() })
I know it's to fix permissions regarding the documentation, but it may lead to issues for some users.
We should prepare a BC note in the upgrade guide.

2022-02-02 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
> +                                    if (referenceType != MembershipReferenceType.API || !PRIMARY_OWNER.name().equals(role.getName())) {
can't you use `isApiPrimaryOwner` method you defined in RoleEntity ?

2022-02-02 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/ApiGroupsResource.java
> +    @ApiOperation(value = "Get API groups mapped to members", notes = "User must have the MANAGE_MEMBERS permission to use this service")
According to your code, you can call this resource without the permission. In that case, one will just receive an empty response.
If we want to throw a 403, we have to use `@Permission` annotation

2022-02-02 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
> +
Don't forget to get the default roles from groups

2022-02-02 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
> +                .filter(group -> group.getRoles().containsKey(RoleScope.API))
naming not clear, it should be called something like `defaultAPIRoleFromPoGroups`

2022-02-03 15:39 UTC, a-cordier commented
@phiz71 I tried to make things clearer following our discussion in an additional commit.

Can you please confirm if you find this somehow more understandable ?

2022-02-15 14:56 UTC, phiz71 approved these changes

2022-02-15 15:25 UTC, merged