Feat/shared apikey prevent updates
gravitee-io/gravitee-api-management pull request #1397
Opened 2022-03-09 15:35 UTC by marcambier

**Issue**

https://github.com/gravitee-io/issues/issues/6799
https://github.com/gravitee-io/issues/issues/6800

**Description**

feat: prevent shared api key update on application subscription screen

This displays a banner and removes the update buttons for shared api key on application subscription screen.

Management API already checks shared API key updates, returning a HTTP 400 if not allowed.

![image](https://user-images.githubusercontent.com/87964124/157474697-38c74f55-b3c2-440b-8ac7-4cac1bf8575b.png)

2022-03-09 17:09 UTC, a-cordier commented
I have a large empty space on the right of the subscriptions list. I don't think that's intended because on master the lists spread across the whole page.

<img width="1517" alt="Screenshot 2022-03-09 at 18 01 23" src="https://user-images.githubusercontent.com/3619261/157493080-aea140c2-8999-4a1a-9475-cfbbf11c1c09.png">

<img width="1517" alt="Screenshot 2022-03-09 at 18 08 13" src="https://user-images.githubusercontent.com/3619261/157493720-44b95fb6-d68e-402a-8c53-6db7294c536d.png">

Chrome Version 99.0.4844.51 (Official Build) (arm64)

2022-03-09 17:10 UTC, a-cordier requested changes

2022-03-09 17:10 UTC, a-cordier commented on gravitee-apim-console-webui/src/management/api-key/api-keys.html
> +    You can renew or revoke the shared API key at application level.
```suggestion
    This subscription uses a shared API key.<br />
    You can renew or revoke the shared API key at the application level.
```

2022-03-09 17:10 UTC, a-cordier commented on gravitee-apim-console-webui/src/management/api-key/api-keys.html
> +    You can renew or revoke the shared API key at application level.
not sure about the `the` though (but looking at usage it appears to be more common)

2022-03-09 17:10 UTC, a-cordier commented on gravitee-apim-console-webui/src/management/api-key/api-keys.controller.ts
> +    return this.isSharedApiKey() ? 'Shared API Key' : 'API Keys';
Should API Key be plural as well ? On the screen it is displayed as a table so i'm thinking it is still a bunch of keys from a user point of view, wdyt ?

2022-03-09 17:13 UTC, a-cordier commented
btw is the quite large space left on the right intended ? I can see it on master but looking at other places lists seem to spread across the whole page width.

<img width="1517" alt="Screenshot 2022-03-09 at 18 01 23" src="https://user-images.githubusercontent.com/3619261/157494499-fd7a04a7-2d3c-4690-a3be-132021329e48.png">

2022-03-10 06:57 UTC, marcambier commented on gravitee-apim-console-webui/src/management/api-key/api-keys.controller.ts
> +    return this.isSharedApiKey() ? 'Shared API Key' : 'API Keys';
I'd better keep it singular.
IMO, it's more clear for user that he use the same API key on all subscriptions, (so, only 1 key at all).
Would be confusing to have `Subscriptions using shared API key**s**` at the plural form

2022-03-10 07:18 UTC, marcambier commented
> btw is the quite large space left on the right intended ? I can see it on master but looking at other places lists seem to spread across the whole page width.

Yes, I think it's intended. Already like that in 3.10 for example.
`gv-forms` style limits max-width to 960px. And it's the same thing on all 'forms' screens (for example, application global settings, application members, ...).
If we want to change that style, I think it's a more global rethinking, to implement the same display on all those screens.

2022-03-10 08:35 UTC, a-cordier approved these changes

2022-03-10 09:28 UTC, merged