feat: allow to revoke a shared API key
gravitee-io/gravitee-api-management pull request #1427
Opened 2022-03-15 09:30 UTC by phiz71

**Issue**

https://github.com/gravitee-io/issues/issues/6818

**Description**

allow to revoke a shared API key on Portal

2022-03-15 09:47 UTC, marcambier requested changes
I think I found a inconsistent scenario :
- Go the your "shared API key" application in portal
- Renew the shared API key twice
- Revoke the shared API key
=> portal shows "no valid shared API key"

- Refresh screen (F5)
=> portal shows a valid API key

2022-03-15 09:47 UTC, marcambier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/openapi.yaml
> +          description: Application does not use shared API key mode
Not sure this error really happens currently, cause the same service is called for revoking an API key (shared, or non-shared)

2022-03-15 10:00 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/openapi.yaml
> +          description: Application does not use shared API key mode
you're right. Copy/paste issue I think ;)

2022-03-15 10:00 UTC, phiz71 commented
> I think I found a inconsistent scenario :
> 
> * Go the your "shared API key" application in portal
> * Renew the shared API key twice
> * Revoke the shared API key
>   => portal shows "no valid shared API key"
> * Refresh screen (F5)
>   => portal shows a valid API key

Ok I see what is happening. I'll fix that

2022-03-16 07:20 UTC, marcambier approved these changes

2022-03-16 10:10 UTC, merged