chore: move mongodb upgrade scripts to monorepo
gravitee-io/gravitee-api-management pull request #1472
Opened 2022-03-21 13:45 UTC by a-cordier

see https://github.com/gravitee-io/issues/issues/7041

2022-03-22 12:23 UTC, gcusnieux approved these changes

2022-03-23 16:57 UTC, phiz71 requested changes

2022-03-23 16:57 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.2/1-rename-view-in-category.js
> +        print('found one')
should be removed ?

2022-03-23 16:57 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.12.0/api-keys-migration.js
> +        keys.replaceOne({id: key._id}, key);
`_` is missing for field name `id`

2022-03-24 09:39 UTC, phiz71 approved these changes

2022-03-24 09:46 UTC, merged