feat: add PATCH method on import API
gravitee-io/gravitee-api-management pull request #1558
Opened 2022-04-05 09:13 UTC by gcusnieux

gravitee-io/issues#7443

2022-04-05 21:20 UTC, brasseld commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/JsonPatch.java
> +    @JsonProperty(required = true)
I think we should do Operation.REPLACE by default.

2022-04-05 21:20 UTC, brasseld commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/JsonPatch.java
> +    String path;
Could it be more explicit like `jsonPath` ?

2022-04-05 21:23 UTC, brasseld reviewed
Cool stuff, I like it!

2022-04-11 07:59 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/PlanServiceImpl.java
> +            if (!plans.isEmpty() && planIds.isEmpty() || planIds.size() < plans.size()) {
If we introduce this change we have to keep in mind that the doc needs to be updated

https://docs.gravitee.io/apim/3.x/apim_publisherguide_import_apis.html#plans

2022-04-11 13:02 UTC, a-cordier approved these changes

2022-04-12 08:39 UTC, a-cordier requested changes

2022-04-12 08:39 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PlanService_MismatchWithApiTest.java
> +        when(planRepository.findByApi(API_ID)).thenReturn(Set.of(plan));
```suggestion

```

2022-04-12 08:39 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/PlanService_MismatchWithApiTest.java
> +        when(planRepository.findByApi(API_ID)).thenReturn(Set.of(plan));
```suggestion
 
```

2022-04-12 15:26 UTC, a-cordier approved these changes

2022-04-12 16:10 UTC, merged