7539: add missing retryWrites configuration
gravitee-io/gravitee-api-management pull request #1734
Opened 2022-05-06 06:51 UTC by Mattiamato

**Issue**

https://github.com/gravitee-io/issues/issues/7539

**Description**

This PR allows to change the default configuration of mongoDB retryWrites. This is required to connect via SSL to AWS DocumentDB since retryWrites should be disabled there (See: https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.retryable-writes)

**Additional context**

Graviteesource Ticket: https://graviteesource.zendesk.com/hc/en-us/requests/4018

2022-05-06 12:39 UTC, gasparir approved these changes

2022-05-06 12:39 UTC, gasparir approved these changes

2022-05-17 08:34 UTC, marcambier requested changes
Thanks a lot for your contribution.
Before we merge it, could you please reword your commit to fit the conventional commit specification ? (https://conventionalcommits.org/)
For example `feat: add mongoDb retryWrites configuration`

2022-05-17 13:18 UTC, marcambier approved these changes

2022-05-17 13:24 UTC, merged