fix: handle API redeployment gracefully
gravitee-io/gravitee-api-management pull request #1895
Opened 2022-05-24 16:23 UTC by a-cordier

see https://github.com/gravitee-io/issues/issues/6948

2022-05-25 08:43 UTC, a-cordier commented
Test scenario
---

One API with a latency policy set to 3 seconds on the request phase, triggering successive redeployment during a quick load test

Before fixing
---
```
running (0m33.0s), 000/250 VUs, 2498 complete and 0 interrupted iterations
contacts ✓ [======================================] 000/250 VUs  30s  00035 iters/s

     data_received..................: 1.8 MB 55 kB/s
     data_sent......................: 272 kB 8.3 kB/s
     dropped_iterations.............: 147509 4471.944806/s
     http_req_blocked...............: avg=142.62µs min=0s    med=4µs   max=6.78ms  p(90)=329.3µs p(95)=378µs   
     http_req_connecting............: avg=121.68µs min=0s    med=0s    max=6.74ms  p(90)=283µs   p(95)=319.29µs
     http_req_duration..............: avg=3.08s    min=3s    med=3.04s max=4.92s   p(90)=3.2s    p(95)=3.35s   
       { expected_response:true }...: avg=3.15s    min=3.03s med=3.1s  max=4.92s   p(90)=3.32s   p(95)=3.58s   
     ✓ { status:200 }...............: avg=3.15s    min=3.03s med=3.1s  max=4.92s   p(90)=3.32s   p(95)=3.58s   
     ✓ { status:500 }...............: avg=3s       min=3s    med=3s    max=3.01s   p(90)=3s      p(95)=3s      
     ✓ { status:503 }...............: avg=3s       min=3s    med=3s    max=3.01s   p(90)=3s      p(95)=3s      
     http_req_failed................: 46.43% ✓ 1160        ✗ 1338 
     http_req_receiving.............: avg=409.69µs min=7µs   med=65µs  max=47.39ms p(90)=778.3µs p(95)=1.66ms  
     http_req_sending...............: avg=26.72µs  min=3µs   med=19µs  max=2.93ms  p(90)=42.3µs  p(95)=52µs    
     http_req_tls_handshaking.......: avg=0s       min=0s    med=0s    max=0s      p(90)=0s      p(95)=0s      
     http_req_waiting...............: avg=3.08s    min=3s    med=3.04s max=4.92s   p(90)=3.2s    p(95)=3.35s   
     http_reqs......................: 2498   75.730417/s
     iteration_duration.............: avg=3.08s    min=3s    med=3.04s max=4.92s   p(90)=3.2s    p(95)=3.35s   
     iterations.....................: 2498   75.730417/s
     vus............................: 250    min=192       max=250
     vus_max........................: 250    min=192       max=250
```
After fixing (with a pending requests timeout set to 5 seconds)
--
running (0m33.0s), 000/250 VUs, 2472 complete and 0 interrupted iterations
contacts ✓ [======================================] 000/250 VUs  30s  00035 iters/s

     data_received..................: 2.9 MB 88 kB/s
     data_sent......................: 269 kB 8.2 kB/s
     dropped_iterations.............: 147535 4469.94689/s
     http_req_blocked...............: avg=44.55µs  min=0s    med=2µs   max=2.84ms  p(90)=262µs  p(95)=322µs  
     http_req_connecting............: avg=36.23µs  min=0s    med=0s    max=2.73ms  p(90)=231µs  p(95)=273µs  
     http_req_duration..............: avg=3.13s    min=3.03s med=3.07s max=5.45s   p(90)=3.27s  p(95)=3.44s  
       { expected_response:true }...: avg=3.13s    min=3.03s med=3.07s max=5.45s   p(90)=3.27s  p(95)=3.44s  
     ✓ { status:200 }...............: avg=3.13s    min=3.03s med=3.07s max=5.45s   p(90)=3.27s  p(95)=3.44s  
     http_req_failed................: 0.00%  ✓ 0          ✗ 2472 
     http_req_receiving.............: avg=634.34µs min=15µs  med=150µs max=39.97ms p(90)=1.51ms p(95)=2.8ms  
     http_req_sending...............: avg=18.43µs  min=3µs   med=12µs  max=429µs   p(90)=31µs   p(95)=46.44µs
     http_req_tls_handshaking.......: avg=0s       min=0s    med=0s    max=0s      p(90)=0s     p(95)=0s     
     http_req_waiting...............: avg=3.13s    min=3.03s med=3.07s max=5.45s   p(90)=3.27s  p(95)=3.44s  
     http_reqs......................: 2472   74.895508/s
     iteration_duration.............: avg=3.13s    min=3.03s med=3.07s max=5.45s   p(90)=3.27s  p(95)=3.44s  
     iterations.....................: 2472   74.895508/s
     vus............................: 250    min=188      max=250
     vus_max........................: 250    min=188      max=250

2022-05-31 11:45 UTC, a-cordier commented
Another test made with dynamic properties triggering a re-deploy every 5 seconds, on a longer period

K6 results
---
```
running (15m02.3s), 0000/2000 VUs, 397622 complete and 0 interrupted iterations
contacts ✓ [======================================] 0000/2000 VUs  15m0s  0003 iters/s

     data_received..................: 97 MB  108 kB/s
     data_sent......................: 38 MB  42 kB/s
     dropped_iterations.............: 52677  58.383596/s
     http_req_blocked...............: avg=8.8µs   min=0s  med=3µs  max=32.38ms p(90)=6µs  p(95)=7µs  
     http_req_connecting............: avg=3.33µs  min=0s  med=0s   max=32.34ms p(90)=0s   p(95)=0s   
     http_req_duration..............: avg=3s      min=3s  med=3s   max=3.13s   p(90)=3s   p(95)=3.01s
       { expected_response:true }...: avg=3s      min=3s  med=3s   max=3.13s   p(90)=3s   p(95)=3.01s
     ✓ { status:200 }...............: avg=3s      min=3s  med=3s   max=3.13s   p(90)=3s   p(95)=3.01s
     http_req_failed................: 0.00%  ✓ 0         ✗ 397622
     http_req_receiving.............: avg=43.04µs min=4µs med=23µs max=25.13ms p(90)=56µs p(95)=73µs 
     http_req_sending...............: avg=23.65µs min=2µs med=12µs max=22.96ms p(90)=25µs p(95)=33µs 
     http_req_tls_handshaking.......: avg=0s      min=0s  med=0s   max=0s      p(90)=0s   p(95)=0s   
     http_req_waiting...............: avg=3s      min=3s  med=3s   max=3.13s   p(90)=3s   p(95)=3.01s
     http_reqs......................: 397622 440.69712/s
     iteration_duration.............: avg=3s      min=3s  med=3s   max=3.13s   p(90)=3s   p(95)=3.01s
     iterations.....................: 397622 440.69712/s
     vus............................: 2000   min=1000    max=2000
     vus_max........................: 2000   min=1000    max=2000
```

Update rate
--
```
13:44:47.273 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:44:52.267 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:44:52.274 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:44:57.269 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:44:57.275 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:45:02.268 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:45:02.271 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:45:07.273 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:45:07.276 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:45:12.267 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:45:12.270 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
13:45:17.271 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - 	- free
13:45:17.279 [gio.sync-4] [893173af-cec4-4396-b173-afcec44396b8] INFO  i.g.g.h.a.m.impl.ApiManagerImpl - API id[893173af-cec4-4396-b173-afcec44396b8] name[api1] version[1] has been updated
```

2022-05-31 12:29 UTC, jhaeyaert requested changes

2022-05-31 12:29 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiContextHandlerFactory.java
> +
Do you think we can use the constructor directly instead of using the reflection ?

2022-05-31 12:29 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> +                pendingRequests.decrementAndGet();
Why is there a decrement at this stage of the request ? Is it a mistake ?

2022-05-31 12:29 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> +                    pendingRequests.decrementAndGet();
Why is there a decrement here ?

2022-05-31 12:29 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> +#  handler:
In Jupiter it will not be named "handler". Do you think we could remove the `handler` part ?

2022-05-31 12:29 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> +
If there are multiple apis stuck and the gateway is shutdown, I'm afraid that timeout will be applied for each api sequentially and could block the stop process for a long period.
I'm wondering if we could find a way execute the stop part in a particular thread (using vertx.setTimer() for example ?).

2022-06-01 10:03 UTC, a-cordier commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> +
@jhaeyaert just wondering, as we now stop immediately in case of a shutdown, do you think it is still relevant to wait in an async manner using setTimer ? As I don't see any dependency to the vertx API in the handler, it felt a bit weird to add one so I prefer to ask

2022-06-07 09:24 UTC, jhaeyaert approved these changes
LGTM.

I'm not a big fan of the implementation of the stopUntil as it blocks the current thread while the timeout is not elapsed (and could occurs for all the api to stop, sequentially) but, let's that that this could be refactored if the need arises 👍

2022-06-07 11:39 UTC, merged