feat(apim): Add support for using APIM Management API as a bridge
gravitee-io/gravitee-api-management pull request #2077
Opened 2022-06-24 13:05 UTC by kamiiiel

**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

2022-06-24 13:53 UTC, brasseld approved these changes

2022-06-29 06:58 UTC, gaetanmaisse requested changes
🤔 
![image](https://user-images.githubusercontent.com/4112568/176371869-6758a33d-d7f3-43a4-8bc7-b6a7eed2b54a.png)

I was introduced to the subject but it's not the case for all APIM members.

@kamiiiel can you please fill the template when you are opening an issue? 

Without any context or explanation about the Why and what you did to test everything is ok nobody from @gravitee-io/apim will feel confident enough to review, approve and merge this PR

2022-07-08 08:29 UTC, phiz71 requested changes
As we still rely on python script to bundle APIM, we have to make the same modification in .circleci/package_bundles.py
https://github.com/gravitee-io/gravitee-api-management/blob/3.18.x/.circleci/package_bundles.py#L460

2022-07-19 06:49 UTC, gaetanmaisse approved these changes

2022-07-19 07:05 UTC, gaetanmaisse commented
@kamiiiel I created an issue for this PR: https://github.com/gravitee-io/issues/issues/8133

Can you update it to fill: 
 -  🦸 Acceptance criteria, with a simple scenario describing how to test this issue I guess
 -  📚 Documentation required, does this "feature" should be listed officially on the doc website? or should we wait for other work on that side etc

2022-07-27 15:06 UTC, gaetanmaisse approved these changes

2022-07-27 15:09 UTC, phiz71 approved these changes

2022-07-27 15:24 UTC, phiz71 commented
⚠️ Change have been made in APIM release process, this PR should be rebase so the modification on the python script can be applied on the new ZX script

2022-07-27 15:24 UTC, phiz71 requested changes
⚠️ Change have been made in APIM release process, this PR should be rebase so the modification on the python script can be applied on the new ZX script

2022-07-28 07:39 UTC, phiz71 approved these changes

2022-07-28 12:15 UTC, ThibaudAV approved these changes

2022-07-28 14:08 UTC, merged