Run JEST E2E tests with JDBC
gravitee-io/gravitee-api-management pull request #2079
Opened 2022-06-24 13:48 UTC by ThibaudAV

**Issue**

https://github.com/gravitee-io/issues/issues/7904

**Description**

Run JEST E2E tests with JDBC 

**Additional context**

---
### 🧪 End-to-End Coverage

| INSTRUCTIONS | BRANCHES |
| :----------: | :------: |
|   38% | 22%   |

A more detailed report has been uploaded to [circleci](https://output.circle-artifacts.com/output/job/3a3d1255-f2ac-40c0-b1f5-d86046cb0d5e/artifacts/0/gravitee-apim-e2e/jacoco/reports/index.html)

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-urkbpwcpqp.chromatic.com)

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.z6.web.core.windows.net/7904-e2e-with-jdbc-run-e2e/index.html)
_Notes_: The deployed app is linked to the management API of APIM master. (Same login and password as APIM master)

2022-06-29 08:40 UTC, ThibaudAV commented
NOTE : JDBC test fail : 

Run 1 : 
```
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.405 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.465 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.405 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.465 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.405 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.465 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.405 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.465 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js

```


Run 2 : 
```
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.171 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.568 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.171 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.568 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
```

Run 3 : 
```
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.316 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.552 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/src/apis/api-quality.spec.js (5.316 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-pages.spec.js (8.552 s)
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-update-with-metadata.spec.js
jest-e2e_1        | FAIL dist/api-test/use-case-test/src/management/publisher/flows/add-condition-on-flows-and-test-them.spec.js
jest-e2e_1        | FAIL dist/api-test/src/imports/api-import-with-metadata.spec.js

```

2022-06-30 07:19 UTC, ThibaudAV commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_18_0/schema_flows.yml
> +              newDataType: nvarchar(256)
🤷‍♂️ or more. wdyt ?

2022-06-30 07:27 UTC, ThibaudAV commented on gravitee-apim-e2e/api-test/src/apis/api-visibility.spec.ts
> -        const apis = await succeed(apiResource.getApisRaw({ envId, orgId }));
🤷‍♂️ 

https://github.com/gravitee-io/gravitee-api-management/blob/81991c699f48cb33a5b418d9aca74e027a44b793/gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/java/io/gravitee/rest/api/management/rest/resource/param/ApisParam.java#L27

2022-06-30 08:01 UTC, ThibaudAV commented on gravitee-apim-e2e/api-test/src/imports/api-import-with-metadata.spec.ts
> +    const deletedApis = [firstExpectedApiId, secondExpectedApiId, thirdExpectedApiId, fourthExpectedApiId].map(
This kind of forgotten makes some test flaky (depending on the execution order) 😁

2022-07-01 07:44 UTC, gaetanmaisse requested changes

2022-07-01 07:44 UTC, gaetanmaisse commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
> +      - file: liquibase/changelogs/v3_18_0/schema_flows.yml
If we target master then it will land on 3.19
```suggestion
      - file: liquibase/changelogs/v3_19_0/schema.yml 
```

2022-07-01 07:44 UTC, gaetanmaisse commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_18_0/schema_flows.yml
> +databaseChangeLog:
We should create a `liquibase/changelogs/v3_19_0/schema.yml`

2022-07-01 07:44 UTC, gaetanmaisse commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/changelogs/v3_18_0/schema_flows.yml
> +              newDataType: nvarchar(256)
To move to a 3_19_0 file

2022-07-01 08:34 UTC, ThibaudAV commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/resources/liquibase/master.yml
> +      - file: liquibase/changelogs/v3_18_0/schema_flows.yml
yes i try to change the target to 3.18

2022-07-01 14:03 UTC, gaetanmaisse approved these changes
Not sure the 1st commit message is still relevant 😁

2022-07-01 15:21 UTC, merged