feat(jupiter): implement api logging support for jupiter
gravitee-io/gravitee-api-management pull request #2104
Opened 2022-06-30 07:04 UTC by jhaeyaert

Implements the logging feature for Jupiter.

<img width="2114" alt="image" src="https://user-images.githubusercontent.com/5955401/176613929-5aac324d-c71c-4af0-96c9-87449a8aa3e6.png">

2022-07-05 15:00 UTC, guillaumelamirand requested changes

2022-07-05 15:00 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggingContext.java
> +    public String getCondition() {
Does that mean we can now apply a condition on top of a logger ?

2022-07-05 18:39 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggingContext.java
> +    public String getCondition() {
Defining a condition on the logging is something already existing in v3 and has just been reimplemented with jupiter.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5955401/177393720-b9d817d7-d00a-484d-a9d0-8ddb0f8d8f80.png">

Or maybe I didn't understood your question 🧐 ?

2022-07-06 10:06 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggingContext.java
> +    public String getCondition() {
To provide more details regarding the add `getCondition()`, I reuse the `ExpressionLanguageConditionFilter` which just requires a `ConditionSupplier` to access the condition. For that, I just had to expose the already existing condition located in the `LoggingContext` to make things working pretty smoothly 🙂

2022-07-06 10:15 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/logging/LoggingContext.java
> +    public String getCondition() {
I wasn't aware of this current capability, thank for the answer

2022-07-06 10:15 UTC, guillaumelamirand approved these changes

2022-07-06 10:36 UTC, merged