Fix/plan selection
gravitee-io/gravitee-api-management pull request #2186
Opened 2022-07-12 09:39 UTC by marcambier

:warning: WIP :warning: 
:warning: DRAFT :warning:

2022-07-15 08:44 UTC, marcambier commented on gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
> -        executionContext.request().metrics().setSecurityToken(clientId);
To confirm : as there is no more JWT CheckSubscriptionPolicy, those 2 request metrics have to be fed by JWTPolicy during its execution

2022-07-18 17:38 UTC, jhaeyaert requested changes
Just 2 minor comments.
I've made all the different tests and seems good, well done 👍

2022-07-18 17:38 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/AuthenticationContext.java
> +    Request getRequest();
Is there any particular reason why you renamed it to `getRequest()` ?
Do you see any issue to keep it to `request()` like we have in the `ExecutionContext` class ?

2022-07-18 17:38 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/security/JwtPlanBasedAuthenticationHandler.java
> +        if (getCustomClientIdClaimName() != null) {
Add check on` claims != null` as it could be `null` if the specified token invalid (and maybe add a unit test as well ?).

2022-07-19 06:58 UTC, marcambier commented on gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/AuthenticationContext.java
> +    Request getRequest();
Yes, that's inconsistent comparing to the ExecutionContext.
I turn it back to `request()` :+1:

2022-07-19 07:04 UTC, marcambier commented on gravitee-apim-gateway/gravitee-apim-gateway-security/gravitee-apim-gateway-security-jwt/src/main/java/io/gravitee/gateway/security/jwt/policy/CheckSubscriptionPolicy.java
> -        executionContext.request().metrics().setSecurityToken(clientId);
We prefered to put it in JwtPlanBasedAuthenticationHandler, as it's simpler that modifying the policy

2022-07-19 07:23 UTC, marcambier commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/security/JwtPlanBasedAuthenticationHandler.java
> +        if (getCustomClientIdClaimName() != null) {
done

2022-07-19 08:01 UTC, ThibaudAV approved these changes

2022-07-19 08:01 UTC, ThibaudAV approved these changes

2022-07-27 06:30 UTC, gaetanmaisse commented
@jhaeyaert good for you now?

2022-07-27 06:32 UTC, jhaeyaert approved these changes

2022-07-27 06:38 UTC, merged