7987 sync api reactor run e2e
gravitee-io/gravitee-api-management pull request #2190
Opened 2022-07-13 06:30 UTC by gcusnieux

**Issue**

https://github.com/gravitee-io/issues/issues/7987

**Description**

A small description of what you did in that PR.

**Additional context**

2022-07-15 09:41 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/jupiter/handlers/api/adapter/invoker/InvokerAdapter.java
> +                        if (!nextEmitter.isDisposed()) {
This should be done here and should be handled through connectionHandlerAdapter. Why did you need it ?

2022-07-15 09:48 UTC, guillaumelamirand requested changes
Only one comment about a new code you've added.
Also I am still seen 1 bug and 1 code smell on Sonar about SyncApiReactor, could you have a look ?

2022-07-18 07:12 UTC, jhaeyaert requested changes

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactor.java
> +        return defer(
Is there any particular reason why you've added a `defer` here ?

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/jupiter/handlers/api/adapter/invoker/InvokerAdapter.java
> +                        }
I'm not sure we should do that here ? The `emitter.onComplete()` is called while the invocation has not been completed yet. It is the responsibility of the `ConnectionHandlerAdapter` to track the completion and call the `emitter.onComplete()` because it is the only one to know when the invocation has been performed (eg: we have access to the v3 `ProxyResponse`).

Is there any particular reason why you've added it here ?

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +import org.junit.runner.RunWith;
Can you make sure to use JUnit5 instead of JUnit4 🙏 ?

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +    public void setUp() {
It is now a good practice in JUnit5 to remove the `public` keyword and leave methods package protected.

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        syncApiReactor.doStart();
This part could be moved in the `init` method. Also, we have started to get used to add the class under test as an attribute named `cut`.

`private SyncApiReactor cut;`

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        verify(groupLifecycleManager, times(0)).stop();
I'm not sure it really covers the cases. Ideally we should be able to check that the call to `stop()` occurs when all pending requests are processed. We should also be able to test that the stop call is forced after the timeout expired (using a `TestScheduler`).

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        assertEquals(syncApiReactor.invokerHooks.size(), 1);
Maybe we could improve the test by checking the instance type of the hook (eg: `TracingHook`). We could also add a test for the `LoggingHook` as well.

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        verify(resourceLifecycleManager, times(1)).stop();
`verify(resourceLifecycleManager)` is equivalent to `verify(resourceLifecycleManager, times(1))`

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        when(ctx.getAttribute(SKIP_SECURITY_CHAIN)).thenReturn(true);
I can see that we always test with `SKIP_SECURITY_CHAIN` set to `true` and there is no check that the security chain has been effectively skipped. 

Also it could be interesting to do some deeper tests around the security chain execution as it is a critical part:
- add a test with the `SKIP_SECURITY_CHAIN` set to `false` to show that the security chain is effectively called.
- make sure that the complete flow is well executed when the security chain pass
- make sure that the flow is executed as expected when the security chain interrupt the execution with a 401.

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        orderedChain.verify(platformFlowChain, times(0)).execute(eq(ctx), eq(ExecutionPhase.RESPONSE));
Same here, the assertion related to the `platformFlowChain` doesn't look good.

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        when(flowChainFactory.createPlatformFlow(eq(api))).thenReturn(platformFlowChain);
You can avoid the `eq(...)` when you have only equality checks, it will make the test simpler to read 🙂

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        orderedChain.verify(platformFlowChain, times(0)).execute(eq(ctx), eq(ExecutionPhase.RESPONSE));
The assertion doesn't look good to me. When an error is encountered, the `platformFlowChain` on `RESPONSE` phase should be executed.
I think the behavior of the `apiErrorProcessorChain` is missing and an NPE is thrown and should be avoided to properly execute the test.

`when(apiErrorProcessorChain.execute(ctx, ExecutionPhase.RESPONSE)).thenReturn(Completable.complete());
`

2022-07-18 07:12 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/test/java/io/gravitee/gateway/jupiter/handlers/api/SyncApiReactorTest.java
> +        InvokerAdapter invokerAdapter = mock(InvokerAdapter.class);
It seems pretty the same for all the tests. Maybe something to move to a private method to improve readability ?

2022-07-19 15:26 UTC, jhaeyaert approved these changes

2022-07-19 16:24 UTC, merged