feat(mock-endpoint): log incoming message content
gravitee-io/gravitee-api-management pull request #2374
Opened 2022-08-29 14:19 UTC by phiz71

**Issue**

https://github.com/gravitee-io/issues/issues/8036

**Description**

Add a new entrypoint: HTTP-Post. This entrypoint creates a async message based on the body of an HTTP request.

2022-08-29 14:23 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +        return Completable.defer(
fromRunnable is enough here and avoid creating extra Completable

2022-08-29 14:25 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/test/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnectorTest.java
> +    void shouldCompleteWithoutDoingAnything() {
could add in the method name why it sould complete withoutdoinganything?

2022-08-29 14:25 UTC, guillaumelamirand reviewed
add few comments

2022-08-29 14:53 UTC, phiz71 commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/test/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnectorTest.java
> +    void shouldCompleteWithoutDoingAnything() {
Yes, copy/paste problem ^^

2022-08-29 14:53 UTC, phiz71 commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +        return Completable.defer(
done 👍🏻

2022-08-29 15:08 UTC, guillaumelamirand approved these changes

2022-08-30 12:28 UTC, jhaeyaert requested changes

2022-08-30 12:28 UTC, jhaeyaert commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +                            new Message() {
Maybe we could move it to its own class file ?

2022-08-30 12:28 UTC, jhaeyaert commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +                                    return ctx.request().headers();
Use `HttpHeaders.create(ctx.request().headers())` instead so we are sure the message produced will have its own instance of headers and any policy that could add / remove header on the message will have no effect on the request's headers.

2022-08-30 12:45 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +                            new Message() {
I have created a DefaultMessage class in gateway api that could be used here .

2022-08-30 14:38 UTC, phiz71 commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +                            new Message() {
I've made the changes

2022-08-30 14:38 UTC, phiz71 commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-http-post/src/main/java/io/gravitee/plugin/entrypoint/http/post/HttpPostEntrypointConnector.java
> +                                    return ctx.request().headers();
I've made the changes

2022-08-31 09:58 UTC, jhaeyaert approved these changes

2022-08-31 09:59 UTC, merged