feat(kafka): add kafka endpoint
gravitee-io/gravitee-api-management pull request #2379
Opened 2022-08-30 10:07 UTC by guillaumelamirand

**Issue**

https://github.com/gravitee-io/issues/issues/8245
https://github.com/gravitee-io/issues/issues/8247

**Description**

Implement basic kafka endpoint for both subscribe and publish mode

**Additional context**

2022-08-30 16:01 UTC, phiz71 requested changes

2022-08-30 16:01 UTC, phiz71 commented on gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-kafka/pom.xml
> +            <version>1.17.3</version>
testcontainers is already defined in dependencyManagement in main pom.xml.
You should bump the version in it and remove the version here

2022-08-30 16:01 UTC, phiz71 commented on .circleci/config.yml
> +            jobName: test-repository
```suggestion
            jobName: test-plugin
```

2022-08-30 16:01 UTC, phiz71 commented on .circleci/config.yml
> +        class: large
medium (default size) should be enough

2022-08-30 16:01 UTC, phiz71 commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/pom.xml
> +
useless because it's already defined in the distribution pom (parent of this one)

2022-08-31 08:26 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-endpoint/gravitee-apim-plugin-endpoint-kafka/pom.xml
> +            <version>1.17.3</version>
Actually I updated the version in the parent pom but forget to remove it here, good catch!

2022-08-31 08:29 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/pom.xml
> +
I don't understand your comment. Parent pom of `gravitee-apim-gateway-standalone-distribution/pom.xml` is standalone and doesn't contain anything as dependencies. In this pom you can also find others services, entrypoints and endpoints...

2022-08-31 08:29 UTC, guillaumelamirand commented on .circleci/config.yml
> +        class: large
Will test it because with kafka you never know!

2022-08-31 08:51 UTC, phiz71 approved these changes

2022-08-31 08:51 UTC, merged