Apim 65/api with webhook
gravitee-io/gravitee-api-management pull request #2608
Opened 2022-10-27 07:22 UTC by marcambier

## Issue

https://graviteecommunity.atlassian.net/browse/APIM-65

2022-10-31 13:31 UTC, guillaumelamirand requested changes

2022-10-31 13:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                    // FIXME : to discuss : is that relevant to copy message headers to request headers ?
You should either create a ticket or remove this FIXME, because it won't never be handled otherwise.

2022-10-31 13:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                            .getComponent(ConnectorConfigurationHelper.class)
This component was meant to be used by factory as a dependencies container. If the need got beyond that I would suggest to create a dedicated bean.

2022-10-31 13:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                            subscriptionConfiguration +
I would suggest to remove the full configuration from here to avoid logging sensitive information.

2022-10-31 13:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/configuration/HttpHeader.java
> +public class HttpHeader {
Why do you need to redefine a map ?

2022-10-31 13:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/resources/schemas/subscriptions/schema-form.json
> +        "id": "urn:jsonschema:io:gravitee:plugin:entrypoint:webhook:configuration:HttpHeader",
You should be able to use a standard map with pattern properties to force string/string content.

2022-10-31 14:16 UTC, ytvnr commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                    // FIXME : to discuss : is that relevant to copy message headers to request headers ?
https://graviteecommunity.atlassian.net/browse/APIM-238

2022-10-31 14:31 UTC, ytvnr commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/resources/schemas/subscriptions/schema-form.json
> +        "id": "urn:jsonschema:io:gravitee:plugin:entrypoint:webhook:configuration:HttpHeader",
https://graviteecommunity.atlassian.net/browse/APIM-239

2022-10-31 14:31 UTC, ytvnr commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/configuration/HttpHeader.java
> +public class HttpHeader {
https://graviteecommunity.atlassian.net/browse/APIM-239

2022-10-31 14:48 UTC, ytvnr commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                            .getComponent(ConnectorConfigurationHelper.class)
injected by constructor

2022-10-31 14:48 UTC, ytvnr commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-webhook/src/main/java/io/gravitee/plugin/entrypoint/webhook/WebhookEntrypointConnector.java
> +                            subscriptionConfiguration +
I now only log the subscription id

2022-11-02 07:55 UTC, guillaumelamirand approved these changes

2022-11-02 08:16 UTC, merged