[Console] Migration plan - Part 3
gravitee-io/gravitee-api-management pull request #2735
Opened 2022-11-24 16:57 UTC by ThibaudAV

## Issue
https://gravitee.atlassian.net/browse/APIM-312

## Description

- Add restriction forme fiels
- Impl Save created Plan 

## Additional context
<img width="664" alt="image" src="https://user-images.githubusercontent.com/4974420/203835771-c1dc8544-3bde-4c4b-8a5a-722dace99463.png">

2022-12-22 17:45 UTC, phiz71 requested changes
I also found that the description field should be required.

line 28 in this file https://github.com/gravitee-io/gravitee-api-management/pull/2735/files#diff-dcfd0a3cdb91ac0f4a8508d7068601002d0886b136904be688846ea0350fde09

2022-12-22 17:45 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/api/portal/plans/plan/edit/2-secure-step/plan-edit-secure-step.component.html
> +  </mat-form-field>
The selection rule is useless for keyless plan, it should be added in the ngContainer

2023-01-03 16:34 UTC, ThibaudAV commented
see with the PO, plan description is no more required

2023-01-04 10:46 UTC, a-cordier approved these changes

2023-01-04 13:32 UTC, merged