fix: add cursor pointer to api in application subscriptions
gravitee-io/gravitee-api-management pull request #2818
Opened 2022-12-14 15:36 UTC by a-cordier

see https://gravitee.atlassian.net/browse/APIM-397

2022-12-14 16:51 UTC, Okhelifi approved these changes
As discussed together I'm disappointed about the scss files usage but "c'est pas ma guerre" 😂

2022-12-14 16:52 UTC, phiz71 requested changes

2022-12-14 16:52 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/application/details/subscriptions/application-subscriptions-list.component.html
> +              <a ng-click="$ctrl.navigateToSubscription(subscription.id)" style="cursor: pointer">
Actually we have the same "error" everywhere in the code.
I think we should think of a larger solution

2022-12-15 08:20 UTC, phiz71 commented
Closing this PR since the bug will be fixed with that PR: https://github.com/gravitee-io/gravitee-api-management/pull/2821

2022-12-15 08:20 UTC, closed without merging