feat(console): add breadcrumb
gravitee-io/gravitee-api-management pull request #2865
Opened 2022-12-27 07:13 UTC by gcusnieux

## Issue

https://graviteecommunity.atlassian.net/browse/APIM-302

## Description

A small description of what you did in that PR.

## Additional context

2023-01-06 08:49 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/components/gio-breadcrumb-router/gio-breadcrumb-router.component.ts
> +      if (JSON.stringify(this.breadcrumbItems) !== JSON.stringify(breadcrumbItems)) {
🛐

2023-01-06 08:55 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/components/gio-breadcrumb-router/gio-breadcrumb-router.component.ts
> +    if (Array.isArray(breadcrumb)) {
wdyt ? 

```
const breadcrumbs = castArray(breadcrumb);
return breadcrumbs.map(...
```

2023-01-06 10:38 UTC, phiz71 requested changes

2023-01-06 10:38 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/api/api-navigation/api-navigation.component.ts
> +    });
You can remove it, it's already done with `this.appendDesign()` (line 89)
_It's probably due to the merge of 3.20.x + a rebase._

2023-01-11 16:26 UTC, ThibaudAV approved these changes

2023-01-11 16:28 UTC, merged