Apim 822 entrypoint permissions
gravitee-io/gravitee-api-management pull request #3144
Opened 2023-02-22 17:35 UTC by jourdiw

## Issue

https://gravitee.atlassian.net/browse/APIM-822

## Description

Add @Permissions to v4.
All entrypoint resources controlled by: Scope = organization, rights = read

## Additional context

2023-02-24 13:30 UTC, gcusnieux approved these changes

2023-02-27 08:36 UTC, ThibaudAV approved these changes

2023-02-27 10:05 UTC, phiz71 requested changes
As we already discussed, we have to check if permissions on /entrypoints and /endpoints resources make sense or not

2023-02-27 10:05 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/connector/EntrypointsResource.java
> +    @Permissions({ @Permission(value = RolePermission.ORGANIZATION_ENTRYPOINT, acls = RolePermissionAction.READ) })
ORGANIZATION_ENTRYPOINT is not meant to be used with connectors, it's about the entrypoints of the gateway when using sharding tags.
I would recommend creating a dedicated permission for connectors, or maybe do not use permissions at all

2023-02-28 09:02 UTC, phiz71 commented
Being authenticated is enough, so we decide to not apply permissions. At least for the moment.

2023-02-28 09:02 UTC, closed without merging