fix: make debug mode work with ssl or haproxy enabled
gravitee-io/gravitee-api-management pull request #3482
Opened 2023-03-30 14:35 UTC by ytvnr

Issue

https://gravitee.atlassian.net/browse/APIM-1381

Description

Do not verify host and disable haproxy by default for debug mode

2023-03-30 14:41 UTC, jhaeyaert requested changes

2023-03-30 14:41 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/reactor/DebugReactor.java
> +        options.setDefaultHost("support-debug.com");
I think it's a little mistake 🙂

2023-03-30 14:41 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/reactor/DebugReactor.java
> +        options.setVerifyHost(true);
I think you want to do the opposite 🙂

2023-03-30 14:42 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/reactor/DebugReactor.java
> +        options.setDefaultHost("support-debug.com");
oupsie

2023-03-30 14:44 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/reactor/DebugReactor.java
> +        options.setVerifyHost(true);
indeed, bad commit ^^

2023-03-30 14:49 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/vertx/VertxDebugConfiguration.java
> +            .withOpenssl(Boolean.TRUE.equals(environment.getProperty("http.ssl.openssl", Boolean.class)))
These 3 ones can be removed as they are already loaded from the environment right?

2023-03-30 14:50 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-debug/src/main/java/io/gravitee/gateway/debug/vertx/VertxDebugConfiguration.java
> +            .withOpenssl(Boolean.TRUE.equals(environment.getProperty("http.ssl.openssl", Boolean.class)))
yes, I kept them as a reminder if they move to debug.http.secured in the future. but I can delete

2023-03-31 08:59 UTC, phiz71 approved these changes

2023-03-31 09:20 UTC, merged