Apim 1329 implement entrypoints
gravitee-io/gravitee-api-management pull request #3565
Opened 2023-04-06 10:22 UTC by gcusnieux

## Issue

https://gravitee.atlassian.net/browse/APIM-1329
https://gravitee.atlassian.net/browse/APIM-1330

## Description

A small description of what you did in that PR.

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-sesojnawco.chromatic.com)

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.z6.web.core.windows.net/apim-1329-implement-entrypoints/index.html)
_Notes_: The deployed app is linked to the management API of APIM master. (Same login and password as APIM master)

2023-04-06 16:44 UTC, ThibaudAV approved these changes

2023-04-07 06:43 UTC, phiz71 requested changes
Multiple things are missing:
 - the pagination has not been implemented
 - the `/endpoints/{endpointId}/moreInformation` exists but is not in the openapi specification
 - `/endpoints/{endpointId}/moreInformation` should be replaced by `/endpoints/{endpointId}/more-information`
 - the responses of the resources don't fit the specification => we should have something like this:
```json
{
  "data": [],
  "metadata": {},
  "links": {}
}
```

2023-04-07 06:43 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +    /plugins/entrypoints/{entrypointId}/subscriptionSchema:
```suggestion
    /plugins/entrypoints/{entrypointId}/subscription-schema:
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an endpoint schema.
```suggestion
                Get the JSON schema that describes the configuration of an endpoint.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an endpoint documentation.
```suggestion
                Get the documentation of an endpoint.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get available endpoints on the platform.
```suggestion
                Get available endpoint types on the platform.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an endpoint.
```suggestion
                Get an endpoint type.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +            summary: Get an endpoint more information
```suggestion
            summary: Get more information about how to use a given endpoint
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                    description: More information of the endpoint
```suggestion
                    description: More information about the endpoint
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an endpoint shared configuration schema.
```suggestion
                Get the JSON schema of the shared part of a given endpoint's configuration.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an entrypoint schema.
```suggestion
                Get the JSON schema that describes the configuration of an entrypoint.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an entrypoint subscription schema.
```suggestion
                Get the JSON schema that describes the subscription to a given entrypoint.
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Get an entrypoint more information.
```suggestion
                Get more information about how to use a given entrypoint
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                    description: More information of the entrypoint
```suggestion
                    description: More information about the entrypoint
```

2023-04-11 13:26 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                    example: data:image/png;base64,aFDqfda
I think we can use a field to specify the fact that it is a binary
```suggestion
                schemaImg:
                    type: string
                    format: base64
                    description: Plugin's schema image as base64.
                    example: data:image/png;base64,aFDqfda
```

2023-04-11 20:14 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/connector/EntrypointsResourceTest.java
> +        assertEquals(2, pagination.getNumberOfItemPerPage());
Question: maybe it would be more interesting to have the number of elements on the current page. Because you can ask for 10 elements but only have 4.
On the other hand, you could have this number by looking at the size of the `data`
Wdyt?

2023-04-11 20:14 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/connector/EntrypointsResourceTest.java
> +        assertNull(links.getLast());
Do you think we should send nothing if there is only one page?
I would suggest this:
```suggestion
        assertTrue(links.getFirst().endsWith("/plugins/entrypoints?page=1&perPage=10);
        assertNull(links.getPrevious());
        assertNull(links.getNext());
        assertTrue(links.getLast().endsWith("/plugins/entrypoints?page=1&perPage=10);
```

2023-04-11 20:14 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/connector/EndpointsResourceTest.java
> +        assertFalse(links.containsKey("last"));
Same comment as for the entrypoints

2023-04-11 20:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/AbstractResource.java
> +        if (paginationParam.getPerPage() < -1) {
would it be possible to validate this value before, to avoid fetching the data if not valid ?

2023-04-12 14:26 UTC, phiz71 approved these changes

2023-04-12 15:06 UTC, merged