Archi 230 cluster plugin
gravitee-io/gravitee-api-management pull request #3587
Opened 2023-04-11 09:59 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-217
https://gravitee.atlassian.net/browse/ARCHI-230

## Description

Use new cluster plugins to deal with healthcheck.

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-gygffssval.chromatic.com)

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.z6.web.core.windows.net/archi-230-cluster-plugin/index.html)
_Notes_: The deployed app is linked to the management API of APIM master. (Same login and password as APIM master)

2023-04-12 17:15 UTC, jhaeyaert requested changes
I've got a first look and I issue some troubles with the `ApiManager` not being well started resulting in an NPE:

```
19:10:22.525 [gio.sync-deployer-1] [] WARN  i.g.g.s.s.process.DefaultSyncManager - An error occurs while executing synchronizer ApiSynchronizer, retrying...
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.apis" is null
	at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.get(ApiManagerImpl.java:284)
	at io.gravitee.gateway.handlers.api.manager.impl.ApiManagerImpl.requiredActionFor(ApiManagerImpl.java:141)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onNext(FlowableGroupBy.java:135)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:173)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:374)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:62)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$State.drainNormal(FlowableGroupBy.java:555)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$State.drain(FlowableGroupBy.java:474)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$State.subscribe(FlowableGroupBy.java:424)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$GroupedUnicast.subscribeActual(FlowableGroupBy.java:341)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:53)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy.subscribeActual(FlowableGroupBy.java:73)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:51)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15959)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:161)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onNext(FlowableGroupBy.java:188)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:324)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:186)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.rxjava3.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15959)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I'll will also take time to check with the Hz cluster mode.

2023-04-12 17:15 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
> +        if (!clusterManager.isPrimaryNode()) {
Since there is no more usage of `Cache`, I'm wondering if we could simply remove the `CacheListener.onEvent` and remove the need to inject the `ClusterManager` here as well?

2023-04-12 17:15 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-heartbeat/src/main/java/io/gravitee/gateway/services/heartbeat/impl/HeartbeatEventPublisher.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(HeartbeatEventPublisher.class);
`@Slf4j` ?

2023-04-12 17:15 UTC, jhaeyaert commented on gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/RepositoryTestSuite.java
> +        //        ApiKeyRepositoryTest.class,
Is that something done on purpose?

2023-04-13 07:29 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
> +        if (!clusterManager.isPrimaryNode()) {
I was asking myself the same thing but as I decided to keep it that way until the distributed sync process is fully operational.

2023-04-13 07:29 UTC, guillaumelamirand commented on gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/management/RepositoryTestSuite.java
> +        //        ApiKeyRepositoryTest.class,
not really, didn't even touch on ApiKey I guess this is coming from my previous sync-process branch.

2023-04-13 15:49 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
> +        if (!clusterManager.isPrimaryNode()) {
I finally removed it!

2023-04-14 08:10 UTC, jhaeyaert approved these changes

2023-04-14 09:12 UTC, merged