Rest api V2 - add GET environments/{envId}/apis/_search
gravitee-io/gravitee-api-management pull request #3723
Opened 2023-04-21 13:38 UTC by ThibaudAV

## Issue

https://gravitee.atlassian.net/browse/APIM-1163

## Description

Search apis with lucene

Work of the search : 
Step 0 : build apiQueryBuilder with value of ApiSearchQuery

Step 1 : find apiIds from lucene indexer from 'query' parameter without any pagination and sorting
Step 2 :(not linked to result of 1st step) if user is not admin, get list of apiIds in their scope and join with Lucene results
Step 3: get APIs page from repository by ids(intersection or Step 1 & Step 2 )  and add pagination and sorting

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ustroqogql.chromatic.com)

2023-04-27 16:51 UTC, phiz71 requested changes

2023-04-27 16:51 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource.java
> +            apiQueryBuilder.addFilter(FIELD_TYPE_VALUE, apiSearchQuery.getIds());
```suggestion
            apiQueryBuilder.addFilter(FIELD_ID, apiSearchQuery.getIds());
```

2023-04-27 16:51 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource_SearchApisTest.java
> +    public void should_return_error_with_wrong_value_for_order_by_param() {
```suggestion
    public void should_return_error_with_wrong_value_for_sort_by_param() {
```

2023-04-27 16:51 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource_SearchApisTest.java
> +    public void should_sort_results_with_order_by_param_asc() {
```suggestion
    public void should_sort_results_with_sort_by_param_asc() {
```

2023-04-27 16:51 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource_SearchApisTest.java
> +    public void should_sort_results_with_order_by_param_desc() {
```suggestion
    public void should_sort_results_with_sort_by_param_desc() {
```

2023-04-27 18:21 UTC, ThibaudAV commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource.java
> +            apiQueryBuilder.addFilter(FIELD_TYPE_VALUE, apiSearchQuery.getIds());
hahaha If only it were that simple . but no without refactor it is well api for a dark unknown reason

2023-04-28 08:57 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApisResource.java
> +            apiQueryBuilder.addFilter(FIELD_TYPE_VALUE, apiSearchQuery.getIds());
Ok, I've looked into the code... it's a bit messy

2023-04-28 11:37 UTC, phiz71 approved these changes

2023-04-28 11:59 UTC, merged