Apim 1198 api v4 for members post
gravitee-io/gravitee-api-management pull request #3791
Opened 2023-04-26 14:10 UTC by loriepisicchio

## Issue

https://gravitee.atlassian.net/browse/APIM-1198

## Description

Implement POST + PUT for API members

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-rvyvaigmpq.chromatic.com)

2023-04-26 15:16 UTC, phiz71 requested changes

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +            summary: Add a member to an API or edit membership
```suggestion
            summary: Add a member to an API
```

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                Add a new member to an API, or edit existing membership.
```suggestion
                Add a new member to an API.
```

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +                    description: User's technical identifier
```suggestion
                    description: Technical identifier for existing user.
```

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApiMembersResource.java
> +        }
```suggestion
        checkRoleIsNotPrimaryOwner(apiMembership.getRoleName());
```

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApiMembersResource_CreateOrUpdateTest.java
> +public class ApiMembersResource_CreateOrUpdateTest extends AbstractResourceTest {
question: should we split into `...createTest` and `...updateTest`?

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApiMembersResource_CreateOrUpdateTest.java
> +        doReturn(environmentEntity).when(environmentService).findByOrgAndIdOrHrid(ORGANIZATION, ENVIRONMENT);
reminder for a future PR, maybe we could move this part into an `AbstractEnvironmentTest `?

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApiMembersResource_CreateOrUpdateTest.java
> +        MembershipService.MembershipRole role = new MembershipService.MembershipRole(RoleScope.API, "OWNER");
you don't use these variables, do you?

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/test/java/io/gravitee/rest/api/management/v4/rest/resource/api/ApiMembersResource_CreateOrUpdateTest.java
> +        MembershipService.MembershipRole role = new MembershipService.MembershipRole(RoleScope.API, "OWNER");
Do you use this variable ?

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +            properties:
You should add `memberId` and `roleName` into a required field

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v4/gravitee-apim-rest-api-management-v4-rest/src/main/resources/management-openapi-v4.yaml
> +            properties:
You should add `roleName` into a required field

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
> +        MembershipService.MembershipReference reference = new MembershipService.MembershipReference(MembershipReferenceType.API, apiId);
I think we should check that we have at least a userId or an externalReference, and send a 400 if it's not the case.
We could have both, but in that case, the userId would take over.

2023-04-26 15:16 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
> +            }
As we are in a creation process, if the user is already associated to the API, we should maybe return a 400.
wdyt ?

2023-04-26 15:36 UTC, loriepisicchio commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/MembershipServiceImpl.java
> +        MembershipService.MembershipReference reference = new MembershipService.MembershipReference(MembershipReferenceType.API, apiId);
Done at ressource level

2023-04-28 06:53 UTC, phiz71 approved these changes

2023-04-28 06:54 UTC, merged