ARCHI-217 distributed sync
gravitee-io/gravitee-api-management pull request #3903
Opened 2023-05-05 15:51 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-217

## Description

This PR aims to implement a way to synchronize gravitee gateways across a gravitee cluster.

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-briwvssxhv.chromatic.com)

2023-05-12 13:20 UTC, ThibaudAV reviewed
Too many changes at once for me to take this topic knowledge or to make a relevant code review. I skip sorry

2023-05-15 08:44 UTC, guillaumelamirand commented
> Too many changes at once for me to take this topic knowledge or to make a relevant code review. I skip sorry

No worries this one is for @jhaeyaert and @remibaptistegio

2023-05-23 05:23 UTC, remibaptistegio requested changes

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/DistributedSynchronizer.java
> +     * @param from the beginning timestamp for this synchronization. If <code>-1</code> a <i>full</i> synchronization will be performed, otherwise a <i>incremental</i> synchronization will be made.
```suggestion
     * @param from the beginning timestamp for this synchronization. If <code>-1</code> a <i>full</i> synchronization will be performed, otherwise an <i>incremental</i> synchronization will be made.
```

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/mapper/ApiMapper.java
> +                log.warn("Error while determining apikey into event payload", e);
```suggestion
                log.warn("Error while determining api into event payload", e);
```

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/mapper/OrganizationMapper.java
> +                log.warn("Error while determining deployed organization into events payload", e);
```suggestion
                log.warn("Error while determining deployed organization into event payload", e);
```

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/mapper/OrganizationMapper.java
> +                    .syncAction(DistributedSyncAction.DEPLOY)
Organisation cannot be "undeployed", that's why you hard coded the "deploy" sync action here ?

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/service/DefaultDistributedSyncService.java
> +                "Distributed sync configuration invalid. No repository configured, check 'distributed_sync.type' value."
```suggestion
                "Distributed sync configuration invalid. No repository configured, check 'distributed-sync.type' value."
```

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/service/DefaultDistributedSyncService.java
> +            if (clusterManager.self().primary()) {
Maybe you could use the method isPrimaryNode() from above to avoid the duplication, wdyt ?

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/service/DefaultDistributedSyncService.java
> +            if (clusterManager.self().primary()) {
Same as above and for all the other method that need to check if this is the primary node, this way, if we need to refactor how we retrieve this information, we only have to do it in one method.

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/service/DefaultDistributedSyncService.java
> +                "Distributed sync configuration invalid. No repository configured, check 'distributed_sync.type' value."
Or maybe change the property name in the DistributedSyncConfiguration if it is supposed to be with an underscore.

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/synchronizer/subscription/DistributedSubscriptionSynchronizer.java
> +                log.debug("Subscriptions of {} apis refreshed in {}ms", count, (System.currentTimeMillis() - launchTime.get()))
Not the same log message as the other DistributedSynchronizer, is there a particular reason ? I think it is a good thing to have the initial sync logged using info log level like you do in the other synchronizer.
Also the code in each DistributedSynchronizer is very similar, do you think it could be refactored to avoid duplication ?

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManager.java
> +                    .andThen(distributedSyncService.storeState(nextFromTime, nextToTime))
Do we call storeState even when distributed sync is not enabled ?

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/common/deployer/ApiDeployerTest.java
> +    private DefaultDistributedSyncService distributedSyncService;
Not needed no ?

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/common/deployer/ApiKeyDeployerTest.java
> +import io.gravitee.gateway.services.sync.process.distributed.service.DefaultDistributedSyncService;
```suggestion
```

2023-05-23 05:23 UTC, remibaptistegio commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/test/java/io/gravitee/gateway/services/sync/process/common/deployer/OrganizationDeployerTest.java
> +import io.gravitee.gateway.services.sync.process.distributed.service.DefaultDistributedSyncService;
I think you could remove this import from your test classes since you are always using the NoopDistributedSyncService.

2023-05-23 07:41 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/mapper/OrganizationMapper.java
> +                    .syncAction(DistributedSyncAction.DEPLOY)
exactly, the action is required but for an organization cannot be undeploy.

2023-05-23 07:43 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/distributed/synchronizer/subscription/DistributedSubscriptionSynchronizer.java
> +                log.debug("Subscriptions of {} apis refreshed in {}ms", count, (System.currentTimeMillis() - launchTime.get()))
Yes, this is due to the original subscription synchronizer which was not executed on the initial phase. I'll fix this one.

2023-05-23 07:53 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/repository/DefaultSyncManager.java
> +                    .andThen(distributedSyncService.storeState(nextFromTime, nextToTime))
In order to make the methods easier to chain, I didn't check the distributed sync status but it will at the end call either NoopDistributedSyncService and do nothing if it is disabled.

2023-05-23 08:23 UTC, remibaptistegio approved these changes

2023-05-30 08:16 UTC, jhaeyaert approved these changes
Left 2 comments but looks good to me.

2023-05-30 08:16 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-localregistry/pom.xml
Can you add a note on localregistry removal to the list of the breaking changes for v4 (even if it has never been documented and maintained)?

2023-05-30 08:16 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
> +
Is it used?

2023-05-30 08:22 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/manager/impl/ApiManagerImpl.java
> +
not at all! I'll remove it.

2023-05-30 08:47 UTC, merged

2023-05-30 09:00 UTC, benoitgravitee commented on gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/distributedsync/model/DistributedEvent.java
> +public class DistributedEvent {
Strange combination, all args, no args, builder, no hashcode and equals.

2023-05-30 09:00 UTC, benoitgravitee commented on gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/distributedsync/model/DistributedSyncState.java
> +public class DistributedSyncState {
same remark as above. Builder often implies immutability, why having setter and no args constructors.

2023-05-30 09:00 UTC, benoitgravitee commented on gravitee-apim-repository/gravitee-apim-repository-redis/src/main/java/io/gravitee/repository/redis/distributedsync/RedisDistributedEventRepository.java
> +                Integer nextCursor = response.get(0).toInteger();
comment or protect, but looks like an unsafe operation

2023-05-30 09:00 UTC, benoitgravitee commented on gravitee-apim-repository/gravitee-apim-repository-redis/src/main/java/io/gravitee/repository/redis/distributedsync/RedisDistributedSyncStateRepository.java
> +    public Maybe<DistributedSyncState> findByClusterId(final String clusterId) {
what is clusterId referring to ?

2023-05-30 09:00 UTC, benoitgravitee commented on gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/distributedsync/DistributedEventRepositoryTest.java
> +            .assertValue(distributedEvent -> {
I assume that means there none or exactly one value

2023-05-30 09:36 UTC, guillaumelamirand commented on gravitee-apim-repository/gravitee-apim-repository-test/src/test/java/io/gravitee/repository/distributedsync/DistributedEventRepositoryTest.java
> +            .assertValue(distributedEvent -> {
assertValue assumes there is exactly one onNext signal.

2023-05-30 09:37 UTC, guillaumelamirand commented on gravitee-apim-repository/gravitee-apim-repository-redis/src/main/java/io/gravitee/repository/redis/distributedsync/RedisDistributedSyncStateRepository.java
> +    public Maybe<DistributedSyncState> findByClusterId(final String clusterId) {
I would say something obvious but the id of the cluster. This is used to retrieve the previous state of the cluster if for example every node crashes or master is reelected.

2023-05-30 09:39 UTC, guillaumelamirand commented on gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/distributedsync/model/DistributedEvent.java
> +public class DistributedEvent {
NoArgs with setter is used for json serialization, allargs and builder is used for conveniency.
No need for hashcode and equals because there is no comparison done anywhere.