chore(ci): create a unique full_release workflow
gravitee-io/gravitee-api-management pull request #3950
Opened 2023-05-11 14:51 UTC by ytvnr

## Description

Rework release process to ease it.

- Remove useless `Lint & Build` jobs for UI during release
- Skip CI when preparing next version commit
- Do a new build to publish new SNAPSHOT after having committed the new version. It will avoid database test containers to fail because a new snapshot has not been pushed
- Create a `slack-announcement` job that take a message a as a parameter
- Rework changelog generation to only be based on JIRA
- Create a `full_release` workflow. We keep the old scripts for now so we are able to simply run a part of the release, in case of error that would not be restartable.
- Reword our internal steps. It became hard to distinguish workflows from jobs and commands:
  - jobs are now prefixed with `job-` and the name only contains `-` (hyphens)
  - commands are now prefixed with `cmd-` and the name only contains `-` (hyphens)
  - workflow are not prefixed to stay readable, and their name only contains `_` (underscores)

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ssafuraklu.chromatic.com)

2023-05-11 19:12 UTC, phiz71 requested changes
I have some remarks but very good job!

2023-05-11 19:12 UTC, phiz71 commented on .circleci/config.yml
>                        echo "<< pipeline.parameters.graviteeio_version >>-SNAPSHOT" > .apim-version.txt
I think we can get rid of the command. If I remember well, it was used to reuse a cache built in a previous job. But we do not work like this now; caches are bound to a single job.

2023-05-11 19:12 UTC, phiz71 commented on .circleci/config.yml
>                    at: .
I would restore cache and attach workspace only if not in dry-run

2023-05-11 19:12 UTC, phiz71 commented on .circleci/config.yml
> +                      - Commit and prepare next version
`job-publish-on-artifactory` uses a `mvn deploy ...` command which will build the project. So I think we could get rid of `job-build` here.

2023-05-11 19:12 UTC, phiz71 commented on .circleci/config.yml
> +            - job-nexus-staging:
I would add a manual validation step because once nexus staging has been done, there is no way back in case we found a pb with a released zip.

2023-05-11 19:12 UTC, phiz71 commented on release/README.adoc
> +`npm run full_release -- --version=3.15.11`
```suggestion
`npm run full_release -- --version=3.15.11`: You can also provide the `--latest` parameter to flag the image as `latest`.
```

2023-05-12 06:48 UTC, ytvnr commented on .circleci/config.yml
> +            - job-nexus-staging:
The goal was to avoid any manual validation, because we often forget and the flow is blocked for no reason.
When releasing with the manual steps, I don't think we check if there is any problem, if the previous steps were ok then we push the button for nexus release, so I think it's the same here.
wdyt @gaetanmaisse ?

2023-05-12 06:56 UTC, ytvnr commented on .circleci/config.yml
> +                      - Commit and prepare next version
good remark !
I'm just wondering if it could be a problem to do the (job-build) and job-publish-on-artifactory here. Do you think there is a risk that we cache items built from the new SNAPSHOT version and that would be used by the following steps ?
Maybe this build and publish of new SNAPSHOT should be done later to be sure we avoid any conflict ?
@gaetanmaisse wdyt ?

2023-05-12 12:57 UTC, gaetanmaisse commented on .circleci/config.yml
> +                      - Commit and prepare next version
@phiz71's feedback makes sense so let's keep only the `job-publish-on-artifactory`. I will push this ;)

2023-05-30 12:08 UTC, gaetanmaisse commented on release/package.json
> +    "full_release": "npm run zx steps/full-release.mjs",
```suggestion
    "full_release": "zx --quiet steps/full-release.mjs",
```

2023-05-30 12:15 UTC, gaetanmaisse commented on .circleci/config.yml
> +            - job-nexus-staging:
I agree with you @ytvnr !

2023-05-30 12:22 UTC, phiz71 commented on .circleci/config.yml
> +            - job-nexus-staging:
Ok, let's do this ;)

2023-05-30 12:23 UTC, gaetanmaisse approved these changes

2023-05-30 12:27 UTC, phiz71 approved these changes

2023-05-30 13:16 UTC, merged