feat: upgrade to spring6
gravitee-io/gravitee-api-management pull request #4020
Opened 2023-05-21 15:57 UTC by jhaeyaert

## Issue

https://gravitee.atlassian.net/browse/ARCHI-216

## Description

Migrate to spring 6. Upgraded dependencies coming from the gravitee-bom (see [pull request](https://github.com/gravitee-io/gravitee-bom/pull/79)):

- Spring 5.3.27 -> 6.0.9
- Spring Security 5.5.8 -> 6.1.0
- Jersey 2.35 -> 3.1.1
- Jetty 9.4.44.v20210927 -> 11.0.15

Move from javax to jakarta:

- jakarta.validation-api 2.0.2 -> 3.0.2
- jakarta.annotation-api 1.3.5 -> 2.1.1
- jakarta.mail 1.6.7 -> 2.0.1
- javax.inject 1 -> jakarta-inject-api 2.0.1
- javax.servlet-api 4.0.1 -> jakarta.servlet-api 6.0.0
- jakarta.transaction-api 1.3.3 -> 2.0.1
- jakarta.activation-api 1.2.2 -> 2.1.2
- jakarta.xml.bind-api 2.3.3 -> 4.0.0
- swagger-jaxrs2 2.2.8 -> swagger-jaxrs2-jakarta 2.2.9

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-xemgxqsanx.chromatic.com)

2023-05-22 09:33 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
> +            - $ref: '#/components/schemas/MetadataMap'
Why do you need the allOf here as there is only one element?

2023-05-22 09:33 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
> +            - $ref: '#/components/schemas/MetadataMap'
Same question here.

2023-05-22 09:34 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
> +public class BasicSecurityConfigurerAdapter {
This Configuration is present three times. Couldn't we find a way to share it ?

2023-05-22 09:35 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/mail/MimeMessageParser.java
> +public class MimeMessageParser {
I don't understand the purpose of this class in a test package?

2023-05-22 09:36 UTC, guillaumelamirand requested changes
Just few comments, nothing much.

2023-05-22 10:53 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
> +            - $ref: '#/components/schemas/MetadataMap'
Yes, it was because a unit test expected a null map instead of an empty one. I've checked with @phiz71 and will revert it back and adapt the unit test. 👍

2023-05-22 10:53 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/resources/portal-openapi.yaml
> +            - $ref: '#/components/schemas/MetadataMap'
Same reason 😜

2023-05-22 10:54 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
> +public class BasicSecurityConfigurerAdapter {
Yes, I do agree. I want it done in a dedicated pull request to avoid mixing migration and enhancement. wdyt?

2023-05-22 10:57 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/mail/MimeMessageParser.java
> +public class MimeMessageParser {
This is because apache commons-email library is not yet migrated to jakarta. I've copy-pasted the MimeMessageParser and moved `javax` to `jakarta` to ease the migration and keep tests untouched.

2023-05-22 11:52 UTC, phiz71 commented
About the Sonar scan for the Rest API, we checked together with @jhaeyaert and it's ok to merge even if the coverage is not ok.
The main reason is that the changes have been done on the security part (BasicSecurityConfigurerAdapter) of each API (MAPI v1, MAPI v2 & Portal API) and it would be a lot of effort for a little value to create unit tests for that.

2023-05-22 18:45 UTC, phiz71 requested changes
What a review!! 659 files! 😅
Maybe such PR would have deserved different commits, to separate the "javax-to-jakarta" refactoring from the rest.

I have asked questions about some modification.

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EmailServiceTest.java
> +import java.io.ByteArrayOutputStream;
required ?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
>  import io.gravitee.rest.api.model.EventType;
Should it be also removed since you added `import io.gravitee.rest.api.model.*;` ?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/main/java/io/gravitee/rest/api/security/csrf/CookieCsrfSignedTokenRepository.java
> +import lombok.AllArgsConstructor;
required?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-security/src/main/java/io/gravitee/rest/api/security/csrf/CookieCsrfSignedTokenRepository.java
> +import org.springframework.security.web.csrf.DeferredCsrfToken;
required?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/src/main/java/io/gravitee/rest/api/portal/rest/mapper/ObjectMapperResolver.java
> +        mapper.registerModule(new JsonNullableModule());
I think you can get rid of this since MetadataMap in no longer nullable

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/pom.xml
> +		</dependency>
Is it still needed?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/main/resources/openapi-configuration.yaml
> +prettyPrint: true
I think it's useless since it is already defined in plugin configuration

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
> +import org.junit.Ignore;
Why has it been added?

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiResource_StopTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
as we are using junit4 in this class, I would rather not change this import

2023-05-22 18:45 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiMembersResource_DeleteTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
as we are using junit4 in this class, I would rather not change this import

2023-05-22 20:04 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EmailServiceTest.java
> +import java.io.ByteArrayOutputStream;
Agree with the `import java.io.ByteArrayOutputStream;` but the 2 other jakarta imports are used in the unit tests. Am I missing something? 🧐

2023-05-22 20:09 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiServiceImpl.java
>  import io.gravitee.rest.api.model.EventType;
When I optimize imports with IntelliJ and reformat the code with prettier it always reappears 🤷🏻‍♂️

2023-05-22 20:14 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/auth/OAuth2AuthenticationResourceTest.java
> +import org.junit.Ignore;
During the migration, I temporarily ignored some tests to go a step further and reactivate them later. I just forgot to remove the import 😅

2023-05-22 20:29 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-rest/pom.xml
> +		</dependency>
It is because a `JSON.java` file is generated and imports it. I'm not sure this JSON.java file is really useful however 🤷🏻‍♂️
Probably something to double-check in a dedicated cleanup phase.

2023-05-23 15:42 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/EmailServiceTest.java
> +import java.io.ByteArrayOutputStream;
My comment was for the ByteArrayOutputStream ;)

2023-05-23 15:45 UTC, phiz71 approved these changes

2023-05-23 15:45 UTC, phiz71 approved these changes

2023-05-23 16:07 UTC, phiz71 approved these changes

2023-05-23 16:30 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/mail/MimeMessageParser.java
> +public class MimeMessageParser {
Ticket created to remember: https://gravitee.atlassian.net/browse/APIM-1765

2023-05-23 16:40 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-portal/gravitee-apim-rest-api-portal-security/src/main/java/io/gravitee/rest/api/portal/security/config/BasicSecurityConfigurerAdapter.java
> +public class BasicSecurityConfigurerAdapter {
https://gravitee.atlassian.net/browse/APIM-1766

2023-05-23 16:40 UTC, merged