feat: add gio-license directive
gravitee-io/gravitee-api-management pull request #4197
Opened 2023-06-07 14:03 UTC by gcusnieux

## Issue

https://gravitee.atlassian.net/browse/APIM-1831

## Description

A small description of what you did in that PR.

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-molykkobqz.chromatic.com)

2023-06-13 14:50 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/shared/components/gio-license/gio-license.directive.ts
> +const featureMoreInformationData = {
wdyt to add it into licenseService ?

2023-06-13 14:54 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/shared/interceptors/replace-env.interceptor.ts
> +    if (req.url.indexOf('{:envId}') === -1) {
what about adding a test for this if ?

2023-06-13 15:00 UTC, ThibaudAV approved these changes
I'm always afraid of this kind of parasitic feature added almost everywhere ^^.

2023-06-14 13:13 UTC, a-cordier requested changes
Just needs renaming the features as below. 

```java
String FEATURE_CUSTOM_ROLES = "apim-custom-roles";
String FEATURE_DEBUG_MODE = "apim-debug-mode";
String FEATURE_SHARDING_TAGS = "apim-sharding-tags";
String FEATURE_OPEN_ID_CONNECT_SSO = "apim-openid-connect-sso";
String FEATURE_AUDIT_TRAIL = "api-audit-trail";
String FEATURE_DCR_REGISTRATION = "apim-dcr-registration";
```

2023-06-15 13:03 UTC, a-cordier commented
Regarding the mockup, I think here the lock should be on audit and not on history and events

<img width="1477" alt="Screenshot 2023-06-15 at 15 00 14" src="https://github.com/gravitee-io/gravitee-api-management/assets/3619261/3fab6a69-16ad-4218-814c-67ffd9c700af">

2023-06-15 13:04 UTC, a-cordier commented
I think there should be a lock here as well
<img width="1477" alt="Screenshot 2023-06-15 at 15 03 34" src="https://github.com/gravitee-io/gravitee-api-management/assets/3619261/646ced9c-ff82-432e-9c84-5710e986d9be">

As in Organization | Audit when the screen is merged

2023-06-15 13:12 UTC, a-cordier requested changes
see comments 👆

2023-06-16 13:17 UTC, merged