feat: list all plugins in UI (manage not deployed plugins in MAPI)
gravitee-io/gravitee-api-management pull request #4263
Opened 2023-06-13 22:47 UTC by remibaptistegio

## Issue

https://gravitee.atlassian.net/browse/ARCHI-250

## Description

Implement the new behavior in MAPI and UI to list all plugins (deployed and not deployed). The implementation part on the UI is just to demonstrate the feature while waiting for final design to be finished.

## Additional context

PR on gravitee-plugin : https://github.com/gravitee-io/gravitee-plugin/pull/107

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-uokrqojaki.chromatic.com)

2023-06-14 08:31 UTC, guillaumelamirand requested changes

2023-06-14 08:31 UTC, guillaumelamirand commented on .run/Rest API - MongoDB.run.xml
> +    <option name="VM_PARAMETERS" value="-Dgravitee.home=$ProjectFileDir$/gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/target/distribution -D
I don't think it would be useful so I tend to remove this "default" value.

2023-06-14 08:31 UTC, guillaumelamirand commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-handler/src/main/java/io/gravitee/plugin/entrypoint/internal/DefaultEntrypointConnectorPluginManager.java
> +    public EntrypointConnectorFactory<?> getFactoryById(String entrypointPluginId, boolean includeNotDeployed) {
I have seen the same mechanism in the [ConnectorPluginManagerImpl](https://github.com/gravitee-io/gravitee-plugin/pull/107/files#diff-cc03966f417c9e1720e5fcf9968b64eef8f59662194c7001831eb86e742d0e40), couldn't you factorize it ?

2023-06-14 08:31 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/platform/plugin/PlatformPluginEntity.java
> +    public boolean isDeployed() {
Could you setup lombok annotation instead ?

2023-06-14 08:31 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +            final Collection<T> plugins = pluginManager.findAll(true);
I would imagine the opposite as default value to keep the same behavior. WDYT?

2023-06-14 08:31 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +        T plugin = pluginManager.get(pluginId, true);
same here?

2023-06-14 08:31 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +            return pluginManager.getSchema(pluginId, true);
Actually as you set up `true` everywhere, I am wondering if it makes sense to have the choice ? Couldn't we just answer with deployed or unemployed and let the caller test the status ?

2023-06-14 08:39 UTC, remibaptistegio commented on .run/Rest API - MongoDB.run.xml
> +    <option name="VM_PARAMETERS" value="-Dgravitee.home=$ProjectFileDir$/gravitee-apim-rest-api/gravitee-apim-rest-api-standalone/gravitee-apim-rest-api-standalone-distribution/target/distribution -D
Oops this should not have been there 😄

2023-06-14 09:36 UTC, remibaptistegio commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +            final Collection<T> plugins = pluginManager.findAll(true);
In fact here we want the Rest API to list all plugins and adapt the UI depending on the value of "deployed" param for each plugin. So it felt right to change the behavior for all services relying on this abstract class and let the UI manage it the way we want.

2023-06-14 09:38 UTC, remibaptistegio commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +            return pluginManager.getSchema(pluginId, true);
The idea here is to keep the default behavior for all the components that do not have an UI. By using this strategy, we can only change MAPI and let the gateway as it is.

2023-06-15 13:08 UTC, remibaptistegio commented on gravitee-apim-plugin/gravitee-apim-plugin-entrypoint/gravitee-apim-plugin-entrypoint-handler/src/main/java/io/gravitee/plugin/entrypoint/internal/DefaultEntrypointConnectorPluginManager.java
> +    public EntrypointConnectorFactory<?> getFactoryById(String entrypointPluginId, boolean includeNotDeployed) {
I've looked and it is used in Entrypoint/Endpoint connector plugin manager, the connector one that you spotted and Api service plugin manager. I'm not sure it is worth it for now. Maybe latter if we had more plugin of this type.

2023-06-15 13:46 UTC, remibaptistegio commented on gravitee-apim-rest-api/gravitee-apim-rest-api-model/src/main/java/io/gravitee/rest/api/model/platform/plugin/PlatformPluginEntity.java
> +    public boolean isDeployed() {
done

2023-06-15 13:47 UTC, remibaptistegio commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/AbstractPluginService.java
> +        T plugin = pluginManager.get(pluginId, true);
Same as previous comment.

2023-06-16 08:54 UTC, a-cordier approved these changes

2023-06-16 09:42 UTC, guillaumelamirand approved these changes

2023-06-16 09:42 UTC, merged