tests(perf): add perf scenario for sync api with apikey plan
gravitee-io/gravitee-api-management pull request #4322
Opened 2023-06-20 07:11 UTC by ytvnr

## Issue

https://gravitee.atlassian.net/browse/APIM-621

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ykuqrnqniv.chromatic.com)

2023-06-20 08:20 UTC, leleueri requested changes
Subscriptions on ApiKey plan are not managed.
I comment only one file but same comment can be applied to all ApiKey simulations

2023-06-20 08:20 UTC, leleueri commented on gravitee-apim-perf/src/scenarios/apikey-api-body-policies/apikey.v3.test.ts
> +  const res = http.get(k6Options.apim.gatewayBaseUrl + data.waitGateway.contextPath);
APIKey is not set to the request.

In addition subscriptions are not managed, we should at least have a subscription a the end of the setup phase.
In the ideal case, we should be able to define the number of subscriptions (so the number of APIKeys) and peek randomly an ApiKey in the simulation.

2023-06-20 08:20 UTC, leleueri commented on gravitee-apim-perf/src/scenarios/apikey-api-body-policies/apikey.v3.test.ts
> +  ApisClient.changeLifecycle(data.api.id, LifecycleAction.STOP, {
Remember to unsubscribe plan here before cleaning everything

2023-06-20 08:20 UTC, leleueri commented on gravitee-apim-perf/src/scenarios/apikey-api-body-policies/apikey.v3.test.ts
> +    PlansFixture.newPlan({ status: PlanStatus.PUBLISHED, security: PlanSecurityType.API_KEY }),
can we force the auto approval to be explicit ?

2023-06-21 07:46 UTC, ytvnr commented on gravitee-apim-perf/src/scenarios/apikey-api-body-policies/apikey.v3.test.ts
> +  const res = http.get(k6Options.apim.gatewayBaseUrl + data.waitGateway.contextPath);
good catch :)

2023-06-21 14:57 UTC, leleueri approved these changes

2023-06-21 15:00 UTC, merged