chore: APIM-2057 Change buttons on Review screen
gravitee-io/gravitee-api-management pull request #4374
Opened 2023-06-21 17:28 UTC by anthonyjgatti

## Issue

https://gravitee.atlassian.net/browse/APIM-2057

## Description

Changed button labels to use Save terminology exclusively, and updated tooltips.

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-lhdickwpak.chromatic.com)

2023-06-22 06:22 UTC, loriepisicchio approved these changes

2023-06-22 06:32 UTC, loriepisicchio requested changes
The CI is failing due to code formatting issue (we are using [Prettier](https://prettier.io/) to check the code formatting)

From the `gravitee-apim-console-webui` directory, run
```
nvm use
npm i
npm run lint:fix
```

And you will also need to update the component harness so that the tests can find the buttons according to the new labels: https://github.com/gravitee-io/gravitee-api-management/blob/4bdf85980db0910b71d3278e697e842c3f76cadf/gravitee-apim-console-webui/src/management/api/creation/v4/steps/step-6-summary/step-6-summary.harness.ts#L26

2023-06-27 07:02 UTC, ThibaudAV approved these changes

2023-06-27 07:15 UTC, ThibaudAV approved these changes
Ha for information :

This commit is not totally valid according to the convention we are trying to respect : 
`chore: APIM-2057 Change buttons on Review screen` 
the title of a commit cannot begin with a capital letter. And if you want to add the jira link you can add it in the commit body. 

If you want to read more, you can search for: `conventional commit`.
Unfortunately, in Apim we haven't yet had the time to install a linter to validate this, but in the plugins it is present and adds a warning to your commits: 
<img width="1145" alt="image" src="https://github.com/gravitee-io/gravitee-api-management/assets/4974420/d3518ca4-3400-4e5c-9815-b1050d6eb357">

And this is likely to become an error soon. So it's not mandatory for the moment, but it's interesting to know ;)

2023-06-27 08:53 UTC, loriepisicchio approved these changes

2023-06-27 14:56 UTC, anthonyjgatti commented
Since this PR we have removed the documentation step so I'm going to close this one and open a new one based on the new step order on master branch.

2023-06-27 14:56 UTC, closed without merging