fix: remove jupiter mode configuration
gravitee-io/gravitee-api-management pull request #4406
Opened 2023-06-23 15:40 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-254

## Description

  - remove jupiterMode configuration
  - rename jupiterModeDefault by v4 emulation engine
  - rename/remove every reference to jupiter mode

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ovzmzalrvk.chromatic.com)

2023-06-27 14:47 UTC, leleueri reviewed
question: As we still have V3 as execution mode, is it safe to remove the ReactorVerticle, and some other Stuff around V3 mode (tests, DebugReactorVerticle, ReactorVerticle...) ?

2023-06-27 14:47 UTC, leleueri commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/ExpressionLanguageConditionFlowTest.java
> +            configuration.getProperty("api.jupiterMode.enabled", Boolean.class, false) &&
Should it be emulateV4Engine instead here ? (If so maybe the default value should be set to true ? :thinking: )
```suggestion
            configuration.getProperty("api.v2.emulateV4Engine.default", Boolean.class, false) &&
```

2023-06-28 07:28 UTC, jhaeyaert requested changes

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/ExecutionMode.java
> +            if (label.equals("jupiter")) {
Is it on purpose for compatibility with the previous API having `executionMode="jupiter"` in the database?

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-env/src/test/java/io/gravitee/gateway/env/TimeoutConfigurationTest.java
> -
The default timeout set to 30s must be explicitly added to the list of breaking changes for v4 (documented but not in the BC list).

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-policy/src/main/java/io/gravitee/gateway/policy/impl/PolicyFactoryImpl.java
>              // Conditional policy are directly managed by Jupiter. ConditionalExecutablePolicy must only be instantiated for v3 execution.
// Conditional policy are directly managed by **v4 emulation engine**. ConditionalExecutablePolicy must only be instantiated for v3 execution.

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/ExpressionLanguageConditionFlowTest.java
> +            configuration.getProperty("api.jupiterMode.enabled", Boolean.class, false) &&
I think the purpose of the old `api.jupiterMode.enabled` was just to enable jupiter and continue to fallback to the v3 engine or jupiter engine depending on the `api.executionMode`.
Sounds correct to remove this imho.

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/flow/ExpressionLanguageConditionFlowTest.java
>      private boolean isJupiterMode() {
`isV2EmulateV4Engine` ?

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/GatewayTestingExtensionTest.java
>              .engine("junit-jupiter")
Should be renamed to `junit-v4-emulation-engine`, .... joking 😂😜

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/GatewayTestingExtensionTest.java
> +            .assertStatistics(stats -> stats.started(6).succeeded(6).aborted(0).skipped(0).failed(0));
Why does succeeded passes from 9 to 6 🧐 ?

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
Does `gatewayMode` still have sense? I thought v4 is now the unique engine and for a v2 api it is only a matter of checking the execution mode (v3 or V4 emulation). I'm not sure to understand why we still need it.

I found `gatewayMode` confusing now that the v4 engine activated by default.

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/flows/FlowPhaseExecutionV3IntegrationTest.java
> +                .awaitDone(2, TimeUnit.SECONDS)
Should probably be increased a bit to make sure we don't have flaky tests in our CI which can be slower than our own computer. Usually, I see a delay between 10 and 30s.

2023-06-28 07:28 UTC, jhaeyaert commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/V4EmulationEngineService.java
> +     * <li>no: V4 emulation engine won't be used, v3 mode is the default mode</li>
Now that v4 will be released maybe we can officially put this in the `gravitee.yaml` and add it to the official user-facing documentation?

2023-06-28 09:07 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/GatewayTestingExtensionTest.java
> +            .assertStatistics(stats -> stats.started(6).succeeded(6).aborted(0).skipped(0).failed(0));
test cases for compatibility mode are deleted so it removes 3 tests.
I would say it's normal

2023-06-28 09:08 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
I think we should keep it but deprecate it
a lot of policies are still using it

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/ExecutionMode.java
> +            }
👍🏻 Good for backward compatibility

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
>      public void shouldDefinitionExecutionModeEqualJupiterWhenJsonContainsJupiter() throws Exception {
Suggestion: maybe we could rename this test with "V4EmulationEngin" and add a test to check that "jupiter" is parsed into V4_EMULATION_ENGINE. WDYT ?

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ExecutionModeUpgrader.java
> +        log.info("{} Jupiter APIs have been migrated to use v4-emulation-engine execution mode", modelCounter);
Suggestion: you could use
```Stream<Api> search(ApiCriteria apiCriteria, Sortable sortable, ApiFieldFilter apiFieldFilter) ``` as it is done in `ApiLoggingConditionUpgrader`. It will handle pagination for you

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ExecutionModeUpgrader.java
> +    private void migrateApiEvents() throws TechnicalException, JsonProcessingException {
question: should we also upgrade the payload of deployment payloads in the `events` collection? Or is it handled in the gateway?

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
> +            final String v2EmulateV4EngineDefault = environment.getProperty("api.v2.emulateV4Engine.default", String.class);
Shouldn't we have a default value here ?

2023-06-28 09:12 UTC, phiz71 commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
> +                if (v2EmulateV4EngineDefault.equalsIgnoreCase("yes") || v2EmulateV4EngineDefault.equalsIgnoreCase("creation_only")) {
Could we use DefaultMode enum to test values ?

2023-06-28 09:22 UTC, ytvnr approved these changes
little remarks in addition to my teammates but looks good to me

2023-06-28 09:22 UTC, ytvnr commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
> +                    // Force the execution mode to JUPITER as required by the environment variable.
```suggestion
                    // Force the execution mode to V4 Emulation as required by the environment variable.
```

2023-06-28 09:22 UTC, ytvnr commented on gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/pathparams/PathParametersV4IntegrationTest.java
> +public class PathParametersV4IntegrationTest extends PathParametersV3IntegrationTest {
Should we precise V4 in the name of the class? (this remarks applies for all tests)
Should we now consider v4 as the de facto and so have:
```suggestion
public class PathParametersIntegrationTest extends PathParametersV3IntegrationTest {
```

2023-06-28 09:31 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/api/portal/details/api-portal-details-danger-zone/api-portal-details-danger-zone.component.spec.ts
> +                  defaultValue: "v4-emulation-engine",
prettier 😛 
```suggestion
                  defaultValue: 'v4-emulation-engine',
```

2023-06-28 09:41 UTC, guillaumelamirand commented
> question: As we still have V3 as execution mode, is it safe to remove the ReactorVerticle, and some other Stuff around V3 mode (tests, DebugReactorVerticle, ReactorVerticle...) ?

ReactorVerticle was used when jupiterEnabled was false, there is no mode jupiterEnabled, so ReactorVerticle won't be used any more, any new request will go the HttpProtocolVerticle and then be dispatched to legacy Engine in case of V3.

2023-06-28 09:46 UTC, guillaumelamirand commented on gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/ExecutionMode.java
> +            if (label.equals("jupiter")) {
Yes, I thought it could be good to keep it here in order to make sure we still support the label in case of import for example. WDYT?

2023-06-28 09:47 UTC, jhaeyaert commented on gravitee-apim-definition/gravitee-apim-definition-model/src/main/java/io/gravitee/definition/model/ExecutionMode.java
> +            if (label.equals("jupiter")) {
Sounds good

2023-06-28 09:47 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-env/src/test/java/io/gravitee/gateway/env/TimeoutConfigurationTest.java
> -
I have started a BC section regarding jupiter renaming.

2023-06-28 09:48 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/test/java/GatewayTestingExtensionTest.java
> +            .assertStatistics(stats -> stats.started(6).succeeded(6).aborted(0).skipped(0).failed(0));
exactly :)

2023-06-28 09:49 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
it is, it allows to set execution mode to V3 automatically on a API without having to do it manually.

It is probably wrongly named but I am not for deprecating it, it is used everywhere we wants to run V3 tests.

2023-06-28 09:50 UTC, guillaumelamirand commented on gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/flows/FlowPhaseExecutionV3IntegrationTest.java
> +                .awaitDone(2, TimeUnit.SECONDS)
I am not the one adding these tests, so make sense but in another PR I believe.

2023-06-28 09:51 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/V4EmulationEngineService.java
> +     * <li>no: V4 emulation engine won't be used, v3 mode is the default mode</li>
Regarding the documentation it is in progress, I will add the config in the gravitee.yaml.

2023-06-28 09:52 UTC, guillaumelamirand commented on gravitee-apim-definition/gravitee-apim-definition-jackson/src/test/java/io/gravitee/definition/jackson/api/ApiDeserializerTest.java
>      public void shouldDefinitionExecutionModeEqualJupiterWhenJsonContainsJupiter() throws Exception {
good point. I'll do it.

2023-06-28 09:53 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/ExecutionModeUpgrader.java
> +        log.info("{} Jupiter APIs have been migrated to use v4-emulation-engine execution mode", modelCounter);
yes, perfect. Will change it.

2023-06-28 09:57 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/junit/stmt/ApiDeployerStatement.java
> +                if (v2EmulateV4EngineDefault.equalsIgnoreCase("yes") || v2EmulateV4EngineDefault.equalsIgnoreCase("creation_only")) {
No accessible from here.

2023-06-28 09:57 UTC, guillaumelamirand commented on gravitee-apim-integration-tests/src/test/java/io/gravitee/apim/integration/tests/http/pathparams/PathParametersV4IntegrationTest.java
> +public class PathParametersV4IntegrationTest extends PathParametersV3IntegrationTest {
I always put V3 /V4 Emulation or V4 in the test just to be explicit.

2023-06-28 10:01 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
I do agree, GatewayMode seems more an ExecutionMode

2023-06-28 11:22 UTC, ytvnr approved these changes

2023-06-28 18:11 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
I suggest to call the field `v2ExecutionMode` and use directly ExecutionMode instead of GatewayMode, wdyt?

2023-06-29 06:36 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-tests-sdk/src/main/java/io/gravitee/apim/gateway/tests/sdk/runner/GatewayRunner.java
> +        if (gatewayMode == GatewayMode.V3) {
It is way more understandable now 👍

2023-06-29 06:36 UTC, jhaeyaert approved these changes

2023-06-29 07:46 UTC, merged