chore: add logs to be able to investigate issues while an exception o…
gravitee-io/gravitee-api-management pull request #4487
Opened 2023-07-03 13:59 UTC by aelamrani

…ccurs during the processing of a streamable processor chain

## Issue

https://gravitee.atlassian.net/browse/APIM-1965

## Description

Added an error log when an issue occur while processing the streamable chain. Currently the error is sent back to the payload of the response but it would be better to have it in our logs to investigate.

## Additional context

2023-07-03 14:02 UTC, jhaeyaert requested changes

2023-07-03 14:02 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/processor/chain/AbstractStreamableProcessorChain.java
> +    private final Logger logger = LoggerFactory.getLogger(EndpointGroupLifecycleManager.class);
`AbstractStreamabledProcessorChain`?
I think you can also opt for lombok @Slf4j to avoid such copy-paste issue 🙂

2023-07-03 14:26 UTC, aelamrani commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/core/processor/chain/AbstractStreamableProcessorChain.java
> +    private final Logger logger = LoggerFactory.getLogger(EndpointGroupLifecycleManager.class);
well spotted - fixed

2023-07-03 14:53 UTC, jhaeyaert approved these changes

2023-07-04 11:45 UTC, gaetanmaisse approved these changes
Should we apply this on master too?

2023-07-05 08:03 UTC, aelamrani commented
@gaetanmaisse yes, I have added the label

2023-07-05 08:04 UTC, merged