Apim 1922 permission 2
gravitee-io/gravitee-api-management pull request #4529
Opened 2023-07-05 11:11 UTC by loriepisicchio

## Issue

https://gravitee.atlassian.net/browse/APIM-1922

## Description

Implement permissions on new API v4 module

2023-07-05 14:45 UTC, Okhelifi approved these changes

2023-07-06 09:54 UTC, jourdiw approved these changes

2023-07-06 10:15 UTC, phiz71 requested changes

2023-07-06 10:15 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/api/apis.module.ts
> +        only: ['api-plan-r', 'api-plan-u'],
Suggestion: I would have used 'api-plan-c'

2023-07-06 11:38 UTC, phiz71 approved these changes

2023-07-06 11:39 UTC, merged