fix: add support for redis ratelimit in DB Less mode
gravitee-io/gravitee-api-management pull request #4949
Opened 2023-08-10 10:25 UTC by kamiiiel

## Issue

https://gravitee.atlassian.net/browse/APIM-2335

2023-08-18 06:24 UTC, gaetanmaisse approved these changes
LGMT, would be great if @sebdevaux can have a look too

2023-08-25 09:01 UTC, jhaeyaert requested changes
Can you have a look at the few minor comments I left?

2023-08-25 09:01 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java
> +        context.setAttribute(ExecutionContext.ATTR_VALIDATE_SUBSCRIPTION, this.configuration.getProperty(ExecutionContext.ATTR_VALIDATE_SUBSCRIPTION, Boolean.class, true));
I don't think it is a good idea to use the constant ExecutionContext.ATTR_VALIDATE_SUBSCRIPTION for getting the configuration. Best is to have a dedicated constant for that to avoid any side effect and make things clearer.

2023-08-25 09:01 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/security/plan/SecurityPlan.java
> +
Can you rename `validateSubscription` into `validateSubscriptionEnabled` or something because it sounds confusing to have it named the same as the method name?

2023-08-25 09:01 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> +  validateSubscription: true  # set to false if you want to skip validating the subscription
I think that you can also comment it as `true` is the default value.

2023-08-30 10:02 UTC, jhaeyaert approved these changes

2023-08-31 21:13 UTC, merged