feat: align Alert Engine CTA with other OS
gravitee-io/gravitee-api-management pull request #5019
Opened 2023-08-18 15:54 UTC by gcusnieux

## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

A small description of what you did in that PR.

## Additional context

2023-08-21 12:34 UTC, loriepisicchio requested changes

2023-08-21 12:34 UTC, loriepisicchio commented on gravitee-apim-console-webui/src/components/gio-side-nav/gio-side-nav.component.ts
> +
The same change must be done in https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-v1-v2-menu.service.ts and https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-console-webui/src/management/api/api-ng-navigation/api-ng-v4-menu.service.ts in order to lock Alerts in API sub-menu

2023-08-22 11:54 UTC, Okhelifi approved these changes

2023-08-22 11:56 UTC, loriepisicchio approved these changes

2023-08-22 13:38 UTC, merged