Console - application general migration - seventh part
gravitee-io/gravitee-api-management pull request #6207
Opened 2023-12-14 13:10 UTC by jansobczynski

## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

Migrating application groups tab

## Additional context
Screenshot:
<img width="990" alt="Screenshot 2023-12-14 at 2 09 26 PM" src="https://github.com/gravitee-io/gravitee-api-management/assets/144100648/af94a262-7eb8-4460-ab00-ca4f700991b6">

2023-12-18 16:47 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/services-ngx/application-user-and-group.service.ts
Not needed right ?

2023-12-19 09:52 UTC, jansobczynski commented on gravitee-apim-console-webui/src/services-ngx/application-user-and-group.service.ts
unused method deleted

2023-12-20 09:09 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/services-ngx/application-user-and-group.service.ts
hum ok. 
But like api service (and one of my previous comment) could you split it into dedicated business :
- `application-memebers.service.ts` 
- and use getGroups from `GroupService`

2023-12-20 09:10 UTC, ThibaudAV commented on gravitee-apim-console-webui/src/services-ngx/application-user-and-group.service.ts
ho and we already have ApplicationMembersService. so this service it's not needed

2023-12-20 09:12 UTC, ThibaudAV requested changes
To change : Remove duplicated service method in ApplicationUserAndGroupService and use the one in `ApplicationMembersService` &  `GroupService` instead

2023-12-20 12:47 UTC, ThibaudAV approved these changes

2023-12-20 13:30 UTC, jansobczynski commented on gravitee-apim-console-webui/src/services-ngx/application-user-and-group.service.ts
done

2023-12-20 13:30 UTC, merged