fix: keep synchronizing the configmaps after websocket disconnect
gravitee-io/gravitee-api-management pull request #7128
Opened 2024-04-03 08:45 UTC by kamiiiel

## Issue

https://gravitee.atlassian.net/browse/GKO-54

2024-04-04 08:24 UTC, jgiovaresco reviewed
It seems this change is breaking something in the tests... could you have a look?

2024-04-06 19:10 UTC, a-cordier commented
Thought after playing around with this. Shouldn't we move the retry mecanism to the kubernetes client ? This way we will focus on connection loss instead of getting at risk of retrying error that will happen forever.

2024-04-08 08:36 UTC, jhaeyaert requested changes

2024-04-08 08:36 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-services/gravitee-apim-gateway-services-sync/src/main/java/io/gravitee/gateway/services/sync/process/kubernetes/fetcher/ConfigMapEventFetcher.java
> +            .repeat();
Can you provide a unit test that reproduces the issue and so, that the fix does the job 🙏?

2024-04-08 09:11 UTC, jhaeyaert commented
> Shouldn't we move the retry mechanism to the Kubernetes client in order to focus on connection loss ?

@a-cordier I do agree with you. It should probably be fixed on the K8S client so it is transparent for every consumers (at least for this situation where the watch completes by itself without error).

2024-04-09 16:08 UTC, a-cordier commented
@jhaeyaert FI the fix has been moved here https://github.com/gravitee-io/gravitee-kubernetes/pull/70

2024-04-09 16:21 UTC, a-cordier commented
fixed in https://github.com/gravitee-io/gravitee-kubernetes/commit/b8e7a3de7cfec544538efb00dacc894fa0b80bd8

2024-04-09 16:22 UTC, a-cordier commented
fixed in https://github.com/gravitee-io/gravitee-kubernetes/commit/b8e7a3de7cfec544538efb00dacc894fa0b80bd8

2024-04-09 16:22 UTC, closed without merging