Finish some page migration
gravitee-io/gravitee-api-management pull request #7135
Opened 2024-04-03 10:55 UTC by ThibaudAV

## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

A small description of what you did in that PR.

## Additional context

2024-04-03 20:09 UTC, phiz71 commented
LGTM but it will deserve the "ready-to-test" label and/or screenshots to be sure everything is ok

2024-04-04 10:45 UTC, phiz71 commented
I've played with the PR environment, and it looks ok.
However, I've noticed that the TopAPIs screens calls the mAPI v1 to search for APIs. As a consequence, we can only put v2 APIs in the top APIs list.
Should call the mAPI v2 ?

2024-04-08 18:22 UTC, ThibaudAV commented
Yes, I hadn't noticed. For your information @pes-spyro-soft-com i'll take the fix into account and rework this part. So that it can do an autocomplete search. without trying to load all the apis

2024-04-09 06:05 UTC, phiz71 requested changes
LGTM, just a few changes to do before approval

2024-04-09 06:05 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/settings/top-apis/add-top-apis-dialog/add-top-apis-dialog.component.ts
> +  // public apis: Api[] = [];
to remove

2024-04-09 06:05 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/settings/top-apis/add-top-apis-dialog/add-top-apis-dialog.component.ts
> +      map((apisRspoinse) => apisRspoinse.data),
apisRspoinse => apisResponse

2024-04-09 07:24 UTC, phiz71 approved these changes

2024-04-09 07:48 UTC, merged