ARCHI-338 add missing environment reference in ApiKey, Subscription and plan
gravitee-io/gravitee-api-management pull request #7559
Opened 2024-05-23 17:01 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-338

## Description

This PR adds a extra attribute in ApiKey, Subscription and Plan repository in order to be able to filter them according to the right tenant.

This is required to secure any call made through the bridge and will solve a major issue when all ApiKey and Subscription are sent to any gateways. Meaning that in Hybrid mode a gateway will see all ApiKey of all Environnement.

## Additional context

2024-05-27 21:24 UTC, phiz71 requested changes
I'm globally ok with your PR.
But I have some concerns about its impact. I can see 3 topics in particular:

1. You are modifying the interface of the repository-api for `PlanRepository`. The name and the signature of the method change.
Will it be a problem for the bridge, assuming that bridge 4.4 must be able to response to bridge clients in version 4.1, 4.2 & 4.3?

2. Feature parity team has worked on the import feature for the 4.4.0. I suspect some conflicts around the plan management. If it's not already the case, I would suggest to have a meeting with them so you can sync your respective work.

3. I saw that you have added the environmentId also in the "xxxEntity" objects. But I'm not sure to see if it's really needed or not. I would have thought that the environmentId was defined at creation time only, and then was never required in the service layer. But I may be wrong. Maybe we can have a quick chat for that point.

2024-05-27 21:24 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/plans/ApiIndexUpgrader.java
> +            .key("environmentId", ascending())
As each upgrader is run only once, I don't know how to force this upgrader to be executed to update an existing index.

2024-05-27 21:24 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/main/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiPlansResource.java
> +import io.gravitee.apim.core.plan.model.Plan;
Is it needed ?

2024-05-27 21:24 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/exceptions/SubscriptionMismatchEnvironmentException.java
> +        return ("Application [" + applicationId + "] and plan [" + planId + "] doesn't bellong to the same environment");
```suggestion
        return ("Application [" + applicationId + "] and plan [" + planId + "] doesn't belong to the same environment");
```

2024-05-27 21:24 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/PlanConverter.java
Why don't you set the environmentId when converting from a PlanEntity to a Plan?
```java
public io.gravitee.definition.model.Plan toPlanDefinition(PlanEntity plan) {
```

2024-05-28 07:48 UTC, guillaumelamirand commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/converter/PlanConverter.java
The io.gravitee.definition.model.Plan is for the gateway, no need of the environment.

2024-05-28 07:53 UTC, phiz71 approved these changes

2024-05-31 06:56 UTC, merged