feat: add documentation page support for V4 APIs
gravitee-io/gravitee-api-management pull request #7648
Opened 2024-05-31 17:26 UTC by kamiiiel

see https://gravitee.atlassian.net/browse/GKO-32
And https://gravitee.atlassian.net/browse/GKO-240

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-zqqajuudjf.chromatic.com)

2024-06-04 16:19 UTC, a-cordier reviewed
From fist test I did, it looks like the HTTP fetcher CRD is not working with V4 (content is not fetched

2024-06-04 16:19 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/api/model/crd/PageCRD.java
> +    // Legacy support
I think we can remove this comment

2024-06-04 16:27 UTC, kamiiiel commented
> From fist test I did, it looks like the HTTP fetcher CRD is not working with V4 (content is not fetched

It is not supported at the moment actually. In the UI it is just saying that it will be available soon

2024-06-07 13:28 UTC, a-cordier commented
> > From fist test I did, it looks like the HTTP fetcher CRD is not working with V4 (content is not fetched
> 
> It is not supported at the moment actually. In the UI it is just saying that it will be available soon

should be good with https://github.com/gravitee-io/gravitee-api-management/pull/7723/files

but then we need to add 
```java
pageSourceDomainService.setContentFromSource(page);
```

[here](https://github.com/gravitee-io/gravitee-api-management/pull/7648/files#diff-7d7687cebf2947972fdbb67eec7d6dd3f61a96f509956847613de4e95657d0e0R113)

2024-06-10 12:25 UTC, a-cordier requested changes

2024-06-10 12:25 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/documentation/domain_service/DocumentationValidationDomainService.java
> +        validatePageContent(organizationId, page);
can we add this satement before calling validatePageContent ?

```java
pageSourceDomainService.setContentFromSource(page);
```

2024-06-10 16:12 UTC, a-cordier approved these changes

2024-06-10 16:12 UTC, merged