feat(console): add enabling portal-next to console settings
gravitee-io/gravitee-api-management pull request #7725
Opened 2024-06-07 19:01 UTC by jourdiw

## Issue

https://gravitee.atlassian.net/browse/APIM-5348

## Description

Add enabling portal next to console

<img width="720" alt="Screenshot 2024-06-07 at 16 27 04" src="https://github.com/gravitee-io/gravitee-api-management/assets/42294616/ad9cd157-5c67-44fb-942a-9bd2c6bbb7a9">

## Additional context

2024-06-17 14:03 UTC, illichso approved these changes

2024-06-17 16:11 UTC, phiz71 requested changes

2024-06-17 16:11 UTC, phiz71 commented on gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.spec.ts
> +    //
missing unit-tests

2024-06-18 14:57 UTC, illichso commented on gravitee-apim-console-webui/src/management/settings/portal-settings/portal-settings.component.spec.ts
> +    //
Done

2024-06-18 15:07 UTC, phiz71 approved these changes

2024-06-18 15:22 UTC, merged