feat: add delete data command handler
gravitee-io/gravitee-api-management pull request #8522
Opened 2024-07-29 16:26 UTC by gcusnieux

## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

A small description of what you did in that PR.

## Additional context

2024-09-11 11:50 UTC, phiz71 requested changes
As seen together, I have made some comments to fix before we can merge.
But what a huge work 💪🏻 !

2024-09-11 11:50 UTC, phiz71 commented on pom.xml
> +        <gravitee-cockpit-api.version>3.2.0-cj-1926-delete-command-SNAPSHOT</gravitee-cockpit-api.version>
Don't forget to merge https://github.com/gravitee-io/gravitee-cockpit-api/pull/197/files first and replace the version here after

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiHeaderRepository.java
> +            jdbcTemplate.update("delete from " + tableName + " where environment_id = ?", environmentId);
Maybe you could update only if rows is not null and not empty ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +            jdbcTemplate.update("delete from " + tableName + " where environment_id = ?", environmentId);
Maybe you could update only if keyIds is not null and not empty ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApiRepository.java
> +            jdbcTemplate.update("delete from " + tableName + " where environment_id = ?", environmentId);
Maybe you could update only if apiIds is not null and not empty ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcApplicationRepository.java
> +            jdbcTemplate.update("delete from " + tableName + " where environment_id = ?", environmentId);
Maybe you could update only if applicationIds is not null and not empty ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcSubscriptionRepository.java
> +            });
why not using a "where subscription_id in" clause ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcGroupRepository.java
> +                jdbcTemplate.update("delete from " + tableName + " where id  IN ( " + inClause + " )", groupIds.toArray());
use "environment_id = " instead

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/upgrade/upgrader/index/integrationjobs/SourceIdStatusIndexUpgrader.java
> +package io.gravitee.repository.mongodb.management.upgrade.upgrader.index.integrationjobs;
check current package name

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandler.java
> +        );
we should not delete them like this. Currently they are not attached to a specific env

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/cockpit/command/handler/DeleteEnvironmentCommandHandler.java
> +                    new BiConsumer<String, List<String>>() {
use lambda for readability

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/search/lucene/DocumentTransformer.java
> +    Document transformForDelete(T indexable);
not necessary

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/media/model/Media.java
> -    }
keep it in the class

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-jdbc/src/main/java/io/gravitee/repository/jdbc/management/JdbcMediaRepository.java
> +    private List<String> deleteWithMetadata(String metadata, String value) throws TechnicalException {
maybe rename in `deleteByField` to avoid confusion

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/MongoMediaRepository.java
> +        );
build this query depending on wether you have an environment or an organization. To be consistent with the JDBC implementation

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management/gravitee-apim-rest-api-management-rest/src/test/java/io/gravitee/rest/api/management/rest/resource/ApiMediaResourceTest.java
> +import io.gravitee.rest.api.service.common.GraviteeContext;
required ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiMetadataResourceTest.java
> +        private final Metadata metadata1 = aCoreMetadata(ENV_ID, API_ID, "key1", "1", "value1", Metadata.MetadataFormat.STRING);
I would have put null instead of ENV_ID

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/CreateApiMetadataUseCaseTest.java
> +    private final String ENV_ID = "env#1";
why changing it ?

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/GetApiMetadataUseCaseTest.java
> +        private final Metadata metadata1 = aMetadata(ENV_ID, API_ID, "key1", "key-1", "value1", Metadata.MetadataFormat.STRING);
I would have put null instead of ENV_ID, because it's an API metadata

2024-09-11 11:50 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MetadataServiceTest.java
> -        verifyNoInteractions(auditService);
why ?

2024-09-11 15:02 UTC, gcusnieux commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MetadataServiceTest.java
> -        verifyNoInteractions(auditService);
@phiz71 I don't know why but before this PR the service prupose two ways for metadata creation : 
- One for default metadata (this one add an audit log)
- Another one for others metadata (without audit log) 

I choose to add one on each creation, but I can change to add add an audit log only for default (environment) metadata if you prefer to keep the same behaviour. Let me know

2024-09-11 15:03 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/rest/api/service/impl/MetadataServiceTest.java
> -        verifyNoInteractions(auditService);
oh no ok, I understand. 👍🏻

2024-09-11 15:12 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/sharedpolicygrouphistory/SharedPolicyGroupHistoryMongoRepositoryImpl.java
> +        log.info("===> FIND group {} / {}", query.toString(), sharedPolicyGroups.size());
Is it really required? If yes, shouldn't it be log.debug ?

2024-09-11 15:12 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiMetadataResourceTest.java
> +        private final Metadata metadata2 = aCoreMetadata(ENV_ID, API_ID, "key2", "2", "value2", Metadata.MetadataFormat.STRING);
here also, it should be null. Actually you should have either ENV_ID, or API_ID, but not both

2024-09-11 15:12 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/test/java/io/gravitee/apim/core/api/use_case/GetApiMetadataUseCaseTest.java
> +        private final Metadata metadata2 = aMetadata(ENV_ID, API_ID, "key2", "key-2", "value2", Metadata.MetadataFormat.STRING);
ENV_ID or API_ID but not both.

2024-09-11 15:19 UTC, gcusnieux commented on gravitee-apim-rest-api/gravitee-apim-rest-api-management-v2/gravitee-apim-rest-api-management-v2-rest/src/test/java/io/gravitee/rest/api/management/v2/rest/resource/api/ApiMetadataResourceTest.java
> +        private final Metadata metadata2 = aCoreMetadata(ENV_ID, API_ID, "key2", "2", "value2", Metadata.MetadataFormat.STRING);
Yes, true. It's manage in the utility `aCoreMetadata` method

2024-09-12 17:34 UTC, gcusnieux commented on gravitee-apim-repository/gravitee-apim-repository-api/src/main/java/io/gravitee/repository/media/model/Media.java
> -    }
> keep it in the class

It's never use

2024-09-17 08:58 UTC, phiz71 reviewed
Very last things :p.
We are almost there !

2024-09-17 08:58 UTC, phiz71 commented on gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/management/internal/sharedpolicygrouphistory/SharedPolicyGroupHistoryMongoRepositoryImpl.java
> +import lombok.extern.slf4j.Slf4j;
Required ?

2024-09-17 08:58 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/GenericNotificationConfigUpgrader.java
> +            .referenceType(genericNotificationConfig.getReferenceType())
Shouldn't we put "ENVIRONMENT" instead of "PORTAL" for the reference type?

2024-09-17 08:58 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/upgrade/upgrader/PortalNotificationConfigUpgrader.java
> +            .referenceType(portalNotificationConfig.getReferenceType())
Shouldn't we put "ENVIRONMENT" instead of "PORTAL" for the reference type?

2024-09-17 10:03 UTC, phiz71 approved these changes

2024-09-17 13:38 UTC, merged