fix(portal-next): fix app list
gravitee-io/gravitee-api-management pull request #8622
Opened 2024-08-09 10:51 UTC by illichso

## Issue

https://gravitee.atlassian.net/browse/APIM-5463

## Description

Fix app list 

## Additional context

<img width="1707" alt="Screenshot 2024-08-09 at 12 51 22" src="https://github.com/user-attachments/assets/6f3d280b-bf8a-4b33-b76e-10ef27f5df5b">

https://github.com/user-attachments/assets/bc906520-42b7-4909-a1ed-a71c86d24d77

2024-08-09 12:26 UTC, jourdiw requested changes
Despite different lengths of titles, the application picture should stay in the same position (upper left) instead of centering between title + owner lines.

2024-08-09 12:26 UTC, jourdiw commented on gravitee-apim-portal-webui-next/src/app/applications/applications.component.ts
> +            })
Doesn't look like your map does anything?

2024-08-09 12:26 UTC, jourdiw commented on gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.html
> +        <div class="m3-title-medium" [matTooltip]="application.name">{{ application.name }}</div>
Only show the tooltip when the name is abbreviated.

2024-08-09 12:26 UTC, jourdiw commented on gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.html
> +    <div class="app-card__description m3-body-medium" [matTooltip]="application.description ? application.description : ''">
Do not put tooltip on description at all. The user can view the description in the Application page to learn more.

2024-08-09 13:14 UTC, illichso commented on gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.html
> +    <div class="app-card__description m3-body-medium" [matTooltip]="application.description ? application.description : ''">
Done

2024-08-09 13:14 UTC, illichso commented on gravitee-apim-portal-webui-next/src/app/applications/applications.component.ts
> +            })
Done

2024-08-09 13:48 UTC, illichso commented on gravitee-apim-portal-webui-next/src/components/application-card/application-card.component.html
> +        <div class="m3-title-medium" [matTooltip]="application.name">{{ application.name }}</div>
Done

2024-08-12 08:08 UTC, jourdiw approved these changes

2024-08-12 08:08 UTC, merged