feat: add member support in Application CRD
gravitee-io/gravitee-api-management pull request #8702
Opened 2024-08-19 07:30 UTC by kamiiiel

see: https://gravitee.atlassian.net/browse/GKO-381

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ndyniubeyr.chromatic.com)

2024-08-20 14:32 UTC, a-cordier requested changes
mostly requesting to remove the DB query in the loop as it does not seem to be used, other comment are up to discussion :)

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +        BaseApplicationEntity application;
shall we use var to match what can be found in other classes of this new package ? (assigning in the try catch)

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
>          if (input.crd.getId() == null) {
I don't know about that one. When we will get the export, there will be an ID in the CRD even if the operator "creates" it, and an update should be perform.

Maybe we should use the same pattern as we use for API WDYT ? (setting the ID or generating it in the operator, and look there if there is something to update or not as done below)

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +        List<String> existingApplicationMembers = memberQueryService
same remark about var, but I can see that there's a lot to update, so I'll make that one a global statement.

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    applicationCrudService.findById(application.getId(), input.auditInfo.environmentId());
do we really need to query the DB in a loop there ? I think we already have the app :)

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    }
I think we could almost skip that part as it will be sanitized in an upcoming PR

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    );
maybe we could move this to some kind of mapUserMember method ? (my sonar plugin complains about complexity)

2024-08-20 14:32 UTC, a-cordier commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +        );
same as above, maybe we could move this to a `removeOrphanMembers` method ?

2024-08-20 15:51 UTC, kamiiiel commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    applicationCrudService.findById(application.getId(), input.auditInfo.environmentId());
I moved this line to the execute method, forgot to remove it in here. Good catch

2024-08-20 17:43 UTC, kamiiiel commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    }
What should we change? we still need to return in here? Just remove the log?

2024-08-20 17:57 UTC, kamiiiel commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +                    );
to avoid converting the source/sourceId to user id twice, I think it is better to keep this code like it is. I simplified it a bit so your IDE doesn't complain

2024-08-21 07:32 UTC, kamiiiel commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/apim/core/application/use_case/ImportApplicationCRDUseCase.java
> +        List<String> existingApplicationMembers = memberQueryService
I'm going to leave this one as it is if you don't mind. Var makes the code very difficult to read. And the IDE doesn't show the variable type (like in Rust) so you should always navigate to the variable declaration or method signature and see what exactly you get in the var.

2024-08-21 08:37 UTC, a-cordier approved these changes

2024-08-21 08:53 UTC, merged