fix: remove auto github fethced pages and http-fetcher content from e…
gravitee-io/gravitee-api-management pull request #9208
Opened 2024-09-25 09:07 UTC by kamiiiel

see: https://gravitee.atlassian.net/browse/GKO-585

2024-10-01 06:52 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiExportServiceImpl.java
> +                iterator.remove();
If you remove the whole page, you will loose the fetcher configuration

2024-10-01 06:52 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiExportServiceImpl.java
> +                "http-fetcher".equals(page.getSource().getType())
Are you sure you cannot have a MARKDOWN with http-fetcher ?

2024-10-01 06:52 UTC, phiz71 commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiExportServiceImpl.java
> +                iterator.remove();
If you remove the system folder from an API, you will loose the LINK pages that are used in the developer portal to display custom links

2024-10-01 08:26 UTC, kamiiiel commented on gravitee-apim-rest-api/gravitee-apim-rest-api-service/src/main/java/io/gravitee/rest/api/service/impl/ApiExportServiceImpl.java
> +                "http-fetcher".equals(page.getSource().getType())
I added the MARKDOWN as well

2024-10-10 11:21 UTC, a-cordier requested changes
Can we reword the commit ? there is a typo in `fetcher`

Also, as discussed with APIM, we will wait fist 4.5.x maintenance release to ship this as an enhancement

2024-10-31 09:48 UTC, a-cordier approved these changes

2024-10-31 09:48 UTC, merged