Issues/6629 conditional policies
gravitee-io/gravitee-api-management pull request #921
Opened 2021-12-08 13:58 UTC by ytvnr

**Issue**

https://github.com/gravitee-io/issues/issues/6629

**Description**

Testable for the moment with directc alls to API (add executionCondition in a flow)

**Additional context**

@gravitee-io/archi we may discuss those topics:
- Dedicated PolicyException thrown when expression evaluation throw exception (to hide to the consumer the expression evaluated)
- it concerns only v2 API and so it's only instantiated through FlowPolicyResolver
- No need to instantiate via SecurityPolicyResolver because it concerns policy at plan level

2021-12-09 06:55 UTC, marcambier approved these changes

2021-12-09 07:07 UTC, gcusnieux approved these changes

2021-12-09 11:13 UTC, brasseld requested changes
Can you please add "integration" tests in container module ?

2021-12-09 14:01 UTC, ytvnr commented
@brasseld done in the last FP :)

2021-12-21 09:46 UTC, ThibaudAV approved these changes
LGTM

2021-12-28 15:56 UTC, a-cordier approved these changes

2022-01-05 08:50 UTC, brasseld approved these changes

2022-01-05 10:03 UTC, merged