feat: add OpenTelemetry feature into Gravitee Node
gravitee-io/gravitee-api-management pull request #9626
Opened 2024-10-21 13:53 UTC by guillaumelamirand

## Issue

https://gravitee.atlassian.net/browse/ARCHI-401

## Description

To be defined .

## Additional context

2024-10-30 15:56 UTC, jhaeyaert requested changes

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +                    notFoundProcessorHook,
`tracingHook`?

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +    private Completable handleNotFound(final MutableExecutionContext ctx, final List<TracingHook> notFoundProcessorHook) {
tracingHook?

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +                });
I'm wondering if we can find a way to avoid paying the cost of this when tracing is disabled? (here we are on the not found but the same applies to all dispatched requests)
I know that there is a NoopTracer behind but still, we create 3 extra lambdas (subscribe, complete or finally, error) + 1 observable request + 1 observable response. I'm concerned about the additional cost it could bring 😬

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +                            processHooks,
When there is a timeout or the client closed the connection before the response is sent back, it looks like there is an issue with the span created for post processor.

![image](https://github.com/user-attachments/assets/df326b24-9407-4048-a0a2-0c8795db5d70)

I'll need your opinion because I didn't well understand how the parent span is retrieved (it looks like this occurs when the Respons phase span isn't created (because of the timeout or cancellation)

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +            List<TracingHook> processHooks = tracingContext.isVerbose() ? List.of(tracingHook) : List.of();
tracingHook?

2024-10-30 15:56 UTC, jhaeyaert commented on docker/quick-setup/opentracing-jaeger-tls/docker-compose.yml
> +      - gravitee_services_opentelemetry_exporter__ssl_keystore_path=/opt/graviteeio-gateway/certs/client-keystore.jks
⚠️ Duplicate '_'

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/hook/MessageHookHelper.java
> +            upstream.flatMap(originalMessage ->
It must be a concatMap to keep sequential execution (flatMap uses prefetch and causes trouble when executing policies on messages).

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/hook/MessageHookHelper.java
> +                    .flatMap(transformMessage ->
Same here -> concatMap must be used instead

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-core/src/main/java/io/gravitee/gateway/reactive/core/hook/HookHelper.java
>                  .flatMap(t -> executeHooks(componentId, hooks, HookPhase.POST, ctx, executionPhase, null, null).andThen(Maybe.just(t)))
Out of scope but related to another comment, should be concatMap instead

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactorFactory.java
> +    protected boolean isApiTracingVerboseEnabled(final Api api) {
As far I understand it, verbose at gateway level impacts not found calls + V2 emulated APIs and it has no consequence on V4 APIs where verbose is managed directly in the API definition.
I first thought that verbosity was an admin choice and then, was overridable for v4 APIs so an admin can prevent API publishers from activating verbose mode (ex: tracing platform not sized, ...). That way it follow the same logic we have for the tracing itself (it doesn't trace if not enabled at gateway level). WDYT about enabling verbose mod if enabled at gateway level + at API V4 level?

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/TcpApiReactor.java
> +            tracingContext
I tested the TCP and there is no trace produced. Is it really in the scope or should we simply exclude it for now?

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
> +                endPhaseTracing(ctx, RESPONSE).blockingAwait();
Not super sexy to have blockingAwait() here 😬

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
> +        return Completable
Same optim here

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
> +        return Completable
We can optimize it a bit by checking if tracing is enabled or not:

```java
if(!tracingContext.isEnabled()) {
    return Completable.complete();
}
        
return Completable
            .fromRunnable(...
```

2024-10-30 15:56 UTC, jhaeyaert commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/DefaultApiReactor.java
> +            .doOnTerminate(() -> computeEndpointResponseTimeMetric(ctx));
Any reason behind this change? doFinally allows handling dispose in addition to error and complete.

2024-10-30 16:15 UTC, jhaeyaert commented
I don't know if it was expected but for V2 API there are not so many traces (maybe that's already the case on v4.5 since the tracing plugin has been migrated to otel, just asking 🤷🏻‍♂️)
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/f85176e5-04ef-4833-a648-f9a9b9fd725c">

However, when V4 emulation is enabled, then tracing is similar to what we can find on a V4 API
<img width="1706" alt="image" src="https://github.com/user-attachments/assets/b26cc3b3-4923-407c-b6d1-8d8575018f20">

2024-11-05 08:14 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactive/reactor/DefaultHttpRequestDispatcher.java
> +                            processHooks,
When generate a timeout, I have the following result :
![image](https://github.com/user-attachments/assets/ea06e947-1d7b-4e4d-b797-fd44f3be698e)
****

How did you get your issue ?

2024-11-05 15:54 UTC, guillaumelamirand commented on gravitee-apim-gateway/gravitee-apim-gateway-handlers/gravitee-apim-gateway-handlers-api/src/main/java/io/gravitee/gateway/reactive/handlers/api/v4/TcpApiReactor.java
> +            tracingContext
see https://gravitee.atlassian.net/browse/ARCHI-430

2024-11-05 16:03 UTC, jhaeyaert approved these changes

2024-11-06 15:50 UTC, merged